# Project root dir, relative to current dir (.|..|../..|…)
MANALA_DIR := $(patsubst %/.,%,$(patsubst %.manala/..,%.,$(patsubst %Makefile,%..,$(lastword $(MAKEFILE_LIST)))))
# Current dir, relative to project root dir (.|dir|dir/dir|…)
MANALA_CURRENT_DIR = $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(MANALA_DIR))%,%,$(CURDIR)))
# Is current dir root ? (|1)
MANALA_CURRENT_ROOT = $(if $(filter .,$(MANALA_CURRENT_DIR)),1)

###########
# Project #
###########

define manala_project_host
{{ .Vars.project.name }}.{{ .Vars.project.domain }}$(if $(1),:{{ .Vars.project.ports_prefix }}$(shell printf "%02d" $(1)))
endef

-include $(MANALA_DIR)/.manala/make/text.mk
-include $(MANALA_DIR)/.manala/make/help.mk
-include $(MANALA_DIR)/.manala/make/os.mk
-include $(MANALA_DIR)/.manala/docker/docker.mk
-include $(MANALA_DIR)/.manala/ansible/ansible.mk
-include $(MANALA_DIR)/.manala/make/try.mk
-include $(MANALA_DIR)/.manala/make/git.mk
-include $(MANALA_DIR)/.manala/make/semver.mk

##########
# Docker #
##########

MANALA_DOCKER_COMPOSE_ENV += \
	MANALA_HOST_OS=$(MANALA_OS) \
	MANALA_HOST_DIR=$(abspath $(MANALA_DIR))
MANALA_DOCKER_COMPOSE_FILE += \
	$(MANALA_DIR)/.manala/docker/compose/term.yaml \
	$(MANALA_DIR)/.manala/docker/compose/init.sysv.yaml \
	$(if $(SYMFONY_IDE), $(MANALA_DIR)/.manala/docker/compose/symfony.yaml)
MANALA_DOCKER_COMPOSE_PROFILE ?= development

# Command
MANALA_DOCKER_COMMAND = exec --user app
MANALA_DOCKER_COMMAND_SERVICE = app

MANALA_DOCKER_COMMAND_DEFAULT_DIR = /srv/app/$(MANALA_CURRENT_DIR)

# Services
{{- if .Vars.system.mysql.version }}
MANALA_DOCKER_DEFAULT_SERVICES += mysql
{{- else if .Vars.system.mariadb.version }}
MANALA_DOCKER_DEFAULT_SERVICES += mariadb
{{- end }}
{{- if .Vars.system.elasticsearch.version }}
MANALA_DOCKER_DEFAULT_SERVICES += elasticsearch
{{- end }}

ifeq ($(MANALA_DOCKER_COMPOSE_PROFILE),development)
MANALA_DOCKER_DEFAULT_SERVICES += mailpit
{{- if or .Vars.system.mysql.version .Vars.system.mariadb.version }}
MANALA_DOCKER_DEFAULT_SERVICES += phpmyadmin
{{- end }}
{{- if .Vars.system.redis.version }}
MANALA_DOCKER_DEFAULT_SERVICES += phpredisadmin
{{- end }}
{{- if .Vars.system.elasticsearch.version }}
MANALA_DOCKER_DEFAULT_SERVICES += elasticvue
{{- end }}
endif

###############
# Environment #
###############

MANALA_HELP += $(call manala_help_section, Environment)

# Docker commands only available *OUTSIDE* docker environment
ifndef MANALA_DOCKER

# Setup commands only available *IN* root directory
ifdef MANALA_CURRENT_ROOT
MANALA_HELP += $(call manala_help,setup,                 Setup environment (DEBUG))
setup: MANALA_DOCKER_DEBUG = $(if $(DEBUG),1)
setup:
	$(manala_docker_compose) up \
		--build \
		--wait
	$(setup)
	$(MAKE) help
endif

MANALA_HELP += $(call manala_help,up,                    Start the environment)
up:
	$(manala_docker_compose) start
	$(MAKE) help.project

MANALA_HELP += $(call manala_help,halt,                  Stop the environment)
halt:
	$(manala_docker_compose) stop

MANALA_HELP += $(call manala_help,reload,                Restart the environment)
reload:
	$(manala_docker_compose) restart
	$(MAKE) help.project

MANALA_HELP += $(call manala_help,sh,                    Shell to the environment (DIR))
sh: MANALA_DOCKER_COMMAND_DIR ?= $(if $(findstring command line,$(origin DIR)),$(DIR))
sh:
	if [ ! -t 0 ] ; then \
		$(call manala_docker_command, --no-TTY) sh -s ; \
	else \
		$(manala_docker_command) sh -c ' \
			if [ -x "$$(command -v zsh)" ] ; then \
				exec zsh --login ; \
			else \
				exec bash --login ; \
			fi \
		' ; \
	fi

MANALA_HELP += $(call manala_help,destroy,               Stop and delete environment)
destroy:
	$(manala_docker_compose) down \
		--rmi local \
		--volumes \
		--remove-orphans

MANALA_HELP += $(call manala_help,docker,                Arbitrary docker compose commands)
ifeq (docker, $(firstword $(MAKECMDGOALS)))
ARGS := $(wordlist 2, $(words $(MAKECMDGOALS)), $(MAKECMDGOALS))
$(eval $(ARGS):;@true)
docker:
	$(manala_docker_compose) $(ARGS)
endif

endif

MANALA_HELP += $(call manala_help,provision,             Provision the environment (TAGS|DIFF|VERBOSE|LIMIT|DEBUG))
provision: SHELL := $(or $(MANALA_DOCKER_SHELL),$(SHELL))
provision: MANALA_ANSIBLE_PLAYBOOK_INVENTORY = $(MANALA_DIR)/.manala/ansible/inventories
provision: MANALA_ANSIBLE_PLAYBOOK_BECOME = 1
provision: MANALA_ANSIBLE_PLAYBOOK_TAGS = $(TAGS)
provision: MANALA_ANSIBLE_PLAYBOOK_CHECK = $(if $(DIFF),1)
provision: MANALA_ANSIBLE_PLAYBOOK_DIFF = $(if $(DIFF),1)
provision: MANALA_ANSIBLE_PLAYBOOK_VERBOSE_MORE = $(if $(VERBOSE),1)
provision: MANALA_ANSIBLE_PLAYBOOK_LIMIT = $(if $(LIMIT),$(LIMIT),development)
provision: MANALA_ANSIBLE_DEBUG = $(if $(DEBUG),1)
provision:
	$(call manala_log, Install ansible galaxy collections)
	$(manala_ansible_galaxy_collection_install) \
		$(MANALA_DIR)/.manala/ansible/collections/requirements.yaml
	$(call manala_log, Run ansible playbook)
	$(manala_ansible_playbook) \
		$(MANALA_DIR)/.manala/ansible/system.yaml

MANALA_HELP += $(call manala_help,provision.apt,         Provision the environment - Apt (DIFF|VERBOSE))
provision.apt: TAGS = apt
provision.apt: provision

{{- if .Vars.system.files }}

MANALA_HELP += $(call manala_help,provision.files,       Provision the environment - Files (DIFF|VERBOSE))
provision.files: TAGS = files
provision.files: provision
{{- end }}

{{- if .Vars.system.nginx.configs }}

MANALA_HELP += $(call manala_help,provision.nginx,       Provision the environment - Nginx (DIFF|VERBOSE))
provision.nginx: TAGS = nginx
provision.nginx: provision
{{- end }}

{{- if .Vars.system.supervisor.configs }}

MANALA_HELP += $(call manala_help,provision.supervisor,  Provision the environment - Supervisor (DIFF|VERBOSE))
provision.supervisor: TAGS = supervisor
provision.supervisor: provision
{{- end }}

{{- if .Vars.system.php.version }}

MANALA_HELP += $(call manala_help,provision.php,         Provision the environment - Php (DIFF|VERBOSE))
provision.php: TAGS = php
provision.php: provision
{{- end }}

MANALA_HELP += $(call manala_help,provision.certificates,Provision the environment - Certificates (DIFF|VERBOSE))
provision.certificates: TAGS = certificates
provision.certificates: MANALA_ANSIBLE_PLAYBOOK_EXTRA_VARS = certificates_prompt=true
provision.certificates: provision

{{ if .Vars.deliveries -}}
##############
# Deliveries #
##############

MANALA_HELP += $(call manala_help_section, Deliveries)

{{ range $delivery := .Vars.deliveries }}

{{- if hasKey $delivery "release_repo" -}}
MANALA_HELP += $(call manala_help,release{{ include "delivery_target" $delivery }},Release {{ include "delivery_help" $delivery }} (AUTHOR))
release{{ include "delivery_target" $delivery }}: SHELL := $(or $(MANALA_DOCKER_SHELL),$(SHELL))
release{{ include "delivery_target" $delivery }}: MANALA_ANSIBLE_PLAYBOOK_INVENTORY = $(MANALA_DIR)/.manala/ansible/inventories/release.yaml
release{{ include "delivery_target" $delivery }}: MANALA_ANSIBLE_PLAYBOOK_LIMIT = {{ include "delivery_group" . }}
release{{ include "delivery_target" $delivery }}: MANALA_ANSIBLE_PLAYBOOK_EXTRA_VARS = $(if $(AUTHOR),"release_author='$(AUTHOR)'")
release{{ include "delivery_target" $delivery }}:
	$(call manala_log, Run ansible playbook)
	$(manala_ansible_playbook) \
		$(MANALA_DIR)/.manala/ansible/release.yaml

{{ end -}}

{{- if hasKey $delivery "deploy_hosts" -}}
MANALA_HELP += $(call manala_help,deploy{{ include "delivery_target" $delivery }},Deploy {{ include "delivery_help" $delivery }} (REF))
deploy{{ include "delivery_target" $delivery }}: SHELL := $(or $(MANALA_DOCKER_SHELL),$(SHELL))
deploy{{ include "delivery_target" $delivery }}: MANALA_ANSIBLE_PLAYBOOK_INVENTORY = $(MANALA_DIR)/.manala/ansible/inventories/deploy.yaml
deploy{{ include "delivery_target" $delivery }}: MANALA_ANSIBLE_PLAYBOOK_LIMIT = {{ include "delivery_group" $delivery }}
deploy{{ include "delivery_target" $delivery }}: MANALA_ANSIBLE_PLAYBOOK_EXTRA_VARS = $(if $(REF),'{"deploy_strategy_git_ref": "$(REF)"}')
deploy{{ include "delivery_target" $delivery }}:
	$(call manala_log, Run ansible playbook)
	$(manala_ansible_playbook) \
		$(MANALA_DIR)/.manala/ansible/deploy.yaml
	{{- if hasKey $delivery "deploy_url" }}
	$(call manala_message_success, Visit {{ $delivery.deploy_url }})
	{{- end }}

{{ end -}}

{{ end }}

{{- end -}}

{{- /* Count deliveries triggers */ -}}
{{- $deliveries_triggers_count := 0 -}}
{{- range $delivery := .Vars.deliveries -}}
	{{- if hasKey $delivery "github_ssh_key_secret" -}}
		{{- $deliveries_triggers_count = $deliveries_triggers_count | add1 -}}
	{{- end -}}
{{- end -}}

{{ if $deliveries_triggers_count -}}
#######################
# Deliveries Triggers #
#######################

MANALA_HELP += $(call manala_help_section, Deliveries Triggers)

{{ range $delivery := .Vars.deliveries }}

{{- if hasKey $delivery "github_ssh_key_secret" -}}

{{- if hasKey $delivery "release_repo" -}}
MANALA_HELP += $(call manala_help,trigger-release{{ include "delivery_target" $delivery }},Trigger release {{ include "delivery_help" $delivery }})
trigger-release{{ include "delivery_target" $delivery }}:
	gh workflow run release \
		{{- if hasKey $delivery "app" }}
		--field app={{ $delivery.app }} \
		{{- end }}
		--field tier={{ $delivery.tier }}

{{ end -}}

{{- if hasKey $delivery "deploy_hosts" -}}
MANALA_HELP += $(call manala_help,trigger-deploy{{ include "delivery_target" $delivery }},Trigger deploy {{ include "delivery_help" $delivery }} (REF))
trigger-deploy{{ include "delivery_target" $delivery }}:
	gh workflow run deploy \
		$(if $(REF),--field ref=$(REF)) \
		{{- if hasKey $delivery "app" }}
		--field app={{ $delivery.app }} \
		{{- end }}
		--field tier={{ $delivery.tier }}

{{ end -}}

{{- if and (hasKey $delivery "release_repo") (hasKey $delivery "deploy_hosts") -}}
MANALA_HELP += $(call manala_help,trigger-release+deploy{{ include "delivery_target" $delivery }},Trigger release + deploy {{ include "delivery_help" $delivery }})
trigger-release+deploy{{ include "delivery_target" $delivery }}:
	gh workflow run release \
		--field deploy=true \
		{{- if hasKey $delivery "app" }}
		--field app={{ $delivery.app }} \
		{{- end }}
		--field tier={{ $delivery.tier }}

{{ end -}}

{{ end -}}

{{ end }}

{{- end -}}

########
# Help #
########

MANALA_HELP_PROJECT = $(MANALA_COLOR_COMMENT)┏(°.°)┛┗(°.°)┓$(MANALA_COLOR_RESET) ♪♫ Let's party ♫♪ $(MANALA_COLOR_COMMENT)┗(°.°)┛┏(°.°)┓$(MANALA_COLOR_RESET)\n
{{- if .Vars.system.nginx.configs }}
MANALA_HELP_PROJECT += $(call manala_help,Http,         http://$(call manala_project_host, 80))
MANALA_HELP_PROJECT += $(call manala_help,Https,        https://$(call manala_project_host, 43))
{{- end }}
{{- if .Vars.system.supervisor.configs }}
MANALA_HELP_PROJECT += $(call manala_help,Supervisor,   http://$(call manala_project_host, 1))
{{- end }}
{{- if or .Vars.system.mysql.version .Vars.system.mariadb.version }}
{{- if .Vars.system.mysql.version }}
MANALA_HELP_PROJECT += $(call manala_help,MySQL,        mysql://root@$(call manala_project_host, 6))
{{- else if .Vars.system.mariadb.version }}
MANALA_HELP_PROJECT += $(call manala_help,MariaDB,      mysql://root@$(call manala_project_host, 6))
{{- end }}
MANALA_HELP_PROJECT += $(call manala_help,PhpMyAdmin,   http://$(call manala_project_host, 79))
{{- end }}
{{- if .Vars.system.elasticsearch.version }}
MANALA_HELP_PROJECT += $(call manala_help,Elasticsearch,http://$(call manala_project_host, 92))
MANALA_HELP_PROJECT += $(call manala_help,Elasticvue,   http://$(call manala_project_host, 78))
{{- end }}
{{- if .Vars.system.redis.version }}
MANALA_HELP_PROJECT += $(call manala_help,PhpRedisAdmin,http://$(call manala_project_host, 81))
{{- end }}
MANALA_HELP_PROJECT += $(call manala_help,Mailpit,      http://$(call manala_project_host, 25))
