# Relative root dir ("."|".."|"../.."|…)
_DIR := $(patsubst %/.,%,$(patsubst %.manala/..,%.,$(patsubst %Makefile,%..,$(lastword $(MAKEFILE_LIST)))))
# Is current dir root ? (""|"1")
_ROOT = $(if $(filter .,$(_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_CURRENT_DIR = $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_DIR))%,%,$(CURDIR)))

###########
# Project #
###########

PROJECT_NAME = {{ .Vars.project.name }}

define project_host
$(PROJECT_NAME).{{ .Vars.project.domain }}$(if $(1),:{{ .Vars.project.ports_prefix }}$(shell printf "%02d" $(1)))
endef

-include $(_DIR)/.manala/make/text.mk
-include $(_DIR)/.manala/make/help.mk
-include $(_DIR)/.manala/make/os.mk
-include $(_DIR)/.manala/docker/make.mk
-include $(_DIR)/.manala/ansible/make.mk
-include $(_DIR)/.manala/make/try.mk
-include $(_DIR)/.manala/make/git.mk
-include $(_DIR)/.manala/make/semver.mk

###############
# Environment #
###############

HELP += $(call help_section, Environment)

# Docker commands only available *OUTSIDE* docker environment
ifndef DOCKER

# Setup commands only available *IN* root directory
ifdef _ROOT
HELP += $(call help,setup,                 Setup environment (DEBUG))
setup:
	$(_docker_compose) up \
		--build \
		--detach \
		--wait
	$(setup)
	$(MAKE) help
endif

HELP += $(call help,up,                    Start the environment)
up:
	$(_docker_compose) start
	$(MAKE) help.project

HELP += $(call help,halt,                  Stop the environment)
halt:
	$(_docker_compose) stop

HELP += $(call help,reload,                Restart the environment)
reload:
	$(_docker_compose) restart
	$(MAKE) help.project

HELP += $(call help,sh,                    Open shell to the environment)
sh:
	$(_docker_compose_exec) \
		sh -c "if [ -x \"$$(command -v zsh)\" ] ; then exec zsh --login ; else exec bash --login ; fi"

HELP += $(call help,destroy,               Stop and delete environment)
destroy:
	$(_docker_compose) down \
		--rmi local \
		--volumes \
		--remove-orphans

HELP += $(call help,docker,                Arbitrary docker compose commands)
ifeq (docker, $(firstword $(MAKECMDGOALS)))
ARGS := $(wordlist 2, $(words $(MAKECMDGOALS)), $(MAKECMDGOALS))
$(eval $(ARGS):;@true)
docker:
	$(_docker_compose) $(ARGS)
endif

endif

HELP += $(call help,provision,             Provision the environment (TAGS|DIFF|VERBOSE|LIMIT))
provision: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
provision: _ANSIBLE_PLAYBOOK_INVENTORY = $(_DIR)/.manala/ansible/inventories
provision: _ANSIBLE_PLAYBOOK_BECOME = 1
provision:
	$(call log, Install ansible galaxy collections)
	$(_ansible_galaxy_collection_install) \
		$(_DIR)/.manala/ansible/collections/requirements.yaml
	$(call log, Run ansible playbook)
	$(_ansible_playbook) \
		$(_DIR)/.manala/ansible/system.yaml

HELP += $(call help,provision.apt,         Provision the environment - Apt (DIFF|VERBOSE))
provision.apt: _ANSIBLE_PLAYBOOK_TAGS = apt
provision.apt: provision

{{- if .Vars.system.files }}

HELP += $(call help,provision.files,       Provision the environment - Files (DIFF|VERBOSE))
provision.files: _ANSIBLE_PLAYBOOK_TAGS = files
provision.files: provision
{{- end }}

{{- if .Vars.system.nginx.configs }}

HELP += $(call help,provision.nginx,       Provision the environment - Nginx (DIFF|VERBOSE))
provision.nginx: _ANSIBLE_PLAYBOOK_TAGS = nginx
provision.nginx: provision
{{- end }}

{{- if .Vars.system.supervisor.configs }}

HELP += $(call help,provision.supervisor,  Provision the environment - Supervisor (DIFF|VERBOSE))
provision.supervisor: _ANSIBLE_PLAYBOOK_TAGS = supervisor
provision.supervisor: provision
{{- end }}

{{- if .Vars.system.php.version }}

HELP += $(call help,provision.php,         Provision the environment - Php (DIFF|VERBOSE))
provision.php: _ANSIBLE_PLAYBOOK_TAGS = php
provision.php: provision
{{- end }}

HELP += $(call help,provision.certificates,Provision the environment - Certificates (DIFF|VERBOSE))
provision.certificates: _ANSIBLE_PLAYBOOK_TAGS = certificates
provision.certificates: _ANSIBLE_PLAYBOOK_EXTRA_VARS = certificates_prompt=true
provision.certificates: provision

{{ if .Vars.deliveries -}}
##############
# Deliveries #
##############

HELP += $(call help_section, Deliveries)

{{ range $delivery := .Vars.deliveries }}

{{- if hasKey $delivery "release_repo" -}}
HELP += $(call help,release{{ include "delivery_target" $delivery }},Release {{ include "delivery_help" $delivery }} (AUTHOR))
release{{ include "delivery_target" $delivery }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
release{{ include "delivery_target" $delivery }}: _ANSIBLE_PLAYBOOK_INVENTORY = $(_DIR)/.manala/ansible/inventories/release.yaml
release{{ include "delivery_target" $delivery }}: _ANSIBLE_PLAYBOOK_LIMIT = {{ include "delivery_group" . }}
release{{ include "delivery_target" $delivery }}: _ANSIBLE_PLAYBOOK_EXTRA_VARS = $(if $(AUTHOR),"release_author='$(AUTHOR)'")
release{{ include "delivery_target" $delivery }}:
	$(call log, Run ansible playbook)
	$(_ansible_playbook) \
		$(_DIR)/.manala/ansible/release.yaml

{{ end -}}

{{- if hasKey $delivery "deploy_hosts" -}}
HELP += $(call help,deploy{{ include "delivery_target" $delivery }},Deploy {{ include "delivery_help" $delivery }} (REF))
deploy{{ include "delivery_target" $delivery }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
deploy{{ include "delivery_target" $delivery }}: _ANSIBLE_PLAYBOOK_INVENTORY = $(_DIR)/.manala/ansible/inventories/deploy.yaml
deploy{{ include "delivery_target" $delivery }}: _ANSIBLE_PLAYBOOK_LIMIT = {{ include "delivery_group" $delivery }}
deploy{{ include "delivery_target" $delivery }}: _ANSIBLE_PLAYBOOK_EXTRA_VARS = $(if $(REF),'{"deploy_strategy_git_ref": "$(REF)"}')
deploy{{ include "delivery_target" $delivery }}:
	$(call log, Run ansible playbook)
	$(_ansible_playbook) \
		$(_DIR)/.manala/ansible/deploy.yaml
	{{- if hasKey $delivery "deploy_url" }}
	$(call message_success, Visit {{ $delivery.deploy_url }})
	{{- end }}

{{ end -}}

{{ end }}

{{- end -}}

{{- /* Count deliveries triggers */ -}}
{{- $deliveries_triggers_count := 0 -}}
{{- range $delivery := .Vars.deliveries -}}
	{{- if hasKey $delivery "github_ssh_key_secret" -}}
		{{- $deliveries_triggers_count = $deliveries_triggers_count | add1 -}}
	{{- end -}}
{{- end -}}

{{ if $deliveries_triggers_count -}}
#######################
# Deliveries Triggers #
#######################

HELP += $(call help_section, Deliveries Triggers)

{{ range $delivery := .Vars.deliveries }}

{{- if hasKey $delivery "github_ssh_key_secret" -}}

{{- if hasKey $delivery "release_repo" -}}
HELP += $(call help,trigger-release{{ include "delivery_target" $delivery }},Trigger release {{ include "delivery_help" $delivery }})
trigger-release{{ include "delivery_target" $delivery }}:
	gh workflow run release \
		{{- if hasKey $delivery "app" }}
		--field app={{ $delivery.app }} \
		{{- end }}
		--field tier={{ $delivery.tier }}

{{ end -}}

{{- if hasKey $delivery "deploy_hosts" -}}
HELP += $(call help,trigger-deploy{{ include "delivery_target" $delivery }},Trigger deploy {{ include "delivery_help" $delivery }} (REF))
trigger-deploy{{ include "delivery_target" $delivery }}:
	gh workflow run deploy \
		$(if $(REF),--field ref=$(REF)) \
		{{- if hasKey $delivery "app" }}
		--field app={{ $delivery.app }} \
		{{- end }}
		--field tier={{ $delivery.tier }}

{{ end -}}

{{- if and (hasKey $delivery "release_repo") (hasKey $delivery "deploy_hosts") -}}
HELP += $(call help,trigger-release+deploy{{ include "delivery_target" $delivery }},Trigger release + deploy {{ include "delivery_help" $delivery }})
trigger-release+deploy{{ include "delivery_target" $delivery }}:
	gh workflow run release \
		--field deploy=true \
		{{- if hasKey $delivery "app" }}
		--field app={{ $delivery.app }} \
		{{- end }}
		--field tier={{ $delivery.tier }}

{{ end -}}

{{ end -}}

{{ end }}

{{- end -}}

########
# Help #
########

HELP_PROJECT = $(COLOR_COMMENT)┏(°.°)┛┗(°.°)┓$(COLOR_RESET) ♪♫ Let's party ♫♪ $(COLOR_COMMENT)┗(°.°)┛┏(°.°)┓$(COLOR_RESET)\n
{{- if .Vars.system.nginx.configs }}
HELP_PROJECT += $(call help,Http,         http://$(call project_host, 80))
HELP_PROJECT += $(call help,Https,        https://$(call project_host, 43))
{{- end }}
{{- if .Vars.system.supervisor.configs }}
HELP_PROJECT += $(call help,Supervisor,   http://$(call project_host, 1))
{{- end }}
{{- if or .Vars.system.mysql.version .Vars.system.mariadb.version }}
{{- if .Vars.system.mysql.version }}
HELP_PROJECT += $(call help,MySQL,        mysql://root@$(call project_host, 6))
{{- else if .Vars.system.mariadb.version }}
HELP_PROJECT += $(call help,MariaDB,      mysql://root@$(call project_host, 6))
{{- end }}
HELP_PROJECT += $(call help,PhpMyAdmin,   http://$(call project_host, 79))
{{- end }}
{{- if .Vars.system.elasticsearch.version }}
HELP_PROJECT += $(call help,Elasticsearch,http://$(call project_host, 92))
HELP_PROJECT += $(call help,Elasticvue,   http://$(call project_host, 78))
{{- end }}
{{- if .Vars.system.redis.version }}
HELP_PROJECT += $(call help,PhpRedisAdmin,http://$(call project_host, 81))
{{- end }}
HELP_PROJECT += $(call help,MailHog,      http://$(call project_host, 25))
