manala:
    description: Elao - Generic infra
    sync:
      - .manala/docker
      - .manala/make
      - .env.dist
      - README.md .manala/README.md

system:
    ansible:
        version: 2.9.2
    terraform:
        version: 0.12.18
