manala:
    description: Elao - Generic application with PHP and Node.js support - Docker
    template: .manala.yaml.tmpl
    sync:
      - .manala/ansible
      - .manala/certificates/ca.crt
      - .manala/certificates/ca.key
      - .manala/docker
      - .manala/github
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @option {"label": "Project name"}
    # @schema {"type": "string", "minLength": 1}
    name: ~
    domain: ela.ooo
    # @schema {"type": "integer", "minimum": 20, "maximum": 654}
    ports_prefix: ~

##########
# System #
##########

system:
    # @option {"label": "System version"}
    # @schema {"enum": [11, 10]}
    version: ~
    # @schema {"type": "string", "pattern": "^[a-zA-Z]+/[a-zA-Z]+$"}
    timezone: Etc/UTC
    locales:
        # @schema {"type": "string"}
        default: C.UTF-8
        # @schema {"items": {"type": "string"}}
        codes: []
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    apt:
        # @schema {"items": {"type": "string"}}
        repositories: []
        # @schema {"items": {"type": "string"}}
        preferences: []
        # @schema {"items": {"type": "string"}}
        packages: []
        # @schema {"items": {"type": "string"}}
        holds: []
    # @schema {"items": {"type": "object"}}
    files: []
    network:
        hosts: {}
    goss:
        # @schema {"enum": [null, "0.3.21"]}
        version: ~
    nginx:
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "template": {"type": "string"},
        #             "file": {"type": "string"},
        #             "config": {"type": "string"}
        #         }
        #     }
        # }
        configs: []
    php:
        # @option {"label": "Php version"}
        # @schema {"enum": [null, 8.2, 8.1, "8.0", 7.4, 7.3, 7.2, 7.1, "7.0", 5.6]}
        version: ~
        # @schema {"items": {"type": "string"}}
        extensions: []
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "template": {"type": "string"},
        #             "file": {"type": "string"},
        #             "config": {"type": ["object", "string"]}
        #         }
        #     }
        # }
        configs: []
        # @schema {
        #     "additionalProperties": {"type": ["string", "integer"]},
        #     "propertyNames": {"pattern": "^[A-Z_]+$"}
        # }
        env: {}
        composer:
            # @schema {"enum": [null, 1]}
            version: ~
    cron:
        # @schema {"items": {"type": "object"}}
        files: []
    supervisor:
        # @schema {"items": {"type": "object"}}
        configs: []
    nodejs:
        # @option {"label": "Nodejs version"}
        # @schema {"enum": [null, 20, 18, 16, 14, 12, 10, 8, 6]}
        version: ~
        # @schema {"items": {"type": "object"}}
        packages: []
        yarn:
            # @schema {"enum": [null, 1]}
            version: ~
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.11, 10.6, 10.5, 10.4, 10.3, 10.2, 10.1]}
        version: ~
    mysql:
        # @option {"label": "MySQL version"}
        # @schema {"enum": [null, "8.0", 5.7]}
        version: ~
    redis:
        # @option {"label": "Redis version"}
        # @schema {"enum": [null, "*"]}
        version: ~
        config: {}
    elasticsearch:
        # @option {"label": "Elasticsearch version"}
        # @schema {"enum": [null, 8, "7.17.12", 7, 6, 5]}
        version: ~
        # @schema {"items": {"type": "string"}}
        plugins: []
    influxdb:
        # @option {"label": "InfluxDB version"}
        # @schema {"enum": [null, "*"]}
        version: ~
        config: {}
        # @schema {"items": {"type": "string"}}
        databases: []
        # @schema {"items": {"type": "object"}}
        users: []
        # @schema {"items": {"type": "object"}}
        privileges: []
    ssh:
        client:
            # @schema {"type": ["null", "string"]}
            config: ~
    docker:
        # @schema {"additionalProperties": true}
        services:
            app:
                ports: []
        mutagen:
            ignore:
                paths: []

##############
# Deliveries #
##############

# @schema {
#     "definitions": {
#         "delivery": {"type": "object", "$id": "#delivery",
#             "additionalProperties": false,
#             "properties": {
#                 "app": {"type": "string", "pattern": "^[\/a-z]+$"},
#                 "tier": {"type": "string", "pattern": "^[\\w-/]+$"},
#                 "ref": {"type": "string", "pattern": "^[\\w-/]+$"},
#                 "release_repo": {"type": "string"},
#                 "release_ref": {"type": "string", "pattern": "^[\\w-/]+$"},
#                 "release_tasks": {"type": "array", "items": {"$ref": "#delivery_task"}},
#                 "release_add": {"type": "array", "items": {"type": "string"}},
#                 "release_remove": {"type": "array", "items": {"type": "string"}},
#                 "release_markup": {"type": "boolean"},
#                 "deploy_hosts": {"type": "array", "items": {"$ref": "#delivery_host"}},
#                 "deploy_dir": {"type": "string"},
#                 "deploy_releases": {"type": "integer"},
#                 "deploy_tasks": {"type": "array", "items": {"$ref": "#delivery_task"}},
#                 "deploy_post_tasks": {"type": "array", "items": {"$ref": "#delivery_task"}},
#                 "deploy_shared_files": {"type": "array", "items": {"type": "string"}},
#                 "deploy_shared_dirs": {"type": "array", "items": {"type": "string"}},
#                 "deploy_writable_dirs": {"type": "array", "items": {"type": "string"}},
#                 "deploy_remove": {"type": "array", "items": {"type": "string"}},
#                 "deploy_url": {"type": "string"},
#                 "github_ssh_key_secret": {"type": "string"}
#             },
#             "dependencies": {
#                 "deploy_hosts": ["deploy_dir"]
#             },
#             "required": ["tier"]
#         },
#         "delivery_task": {"type": "object", "$id": "#delivery_task",
#             "additionalProperties": false,
#             "properties": {
#                 "shell": {"type": "string"},
#                 "when": {"type": "string"}
#             }
#         },
#         "delivery_host": {"type": "object", "$id": "#delivery_host",
#             "additionalProperties": true,
#             "properties": {
#                 "ssh_host": {"type": "string", "format": "hostname"},
#                 "ssh_user": {"type": "string"},
#                 "ssh_args": {"type": "string"}
#             },
#             "required": ["ssh_host"]
#         }
#     },
#     "items": {"$ref": "#delivery"}
# }
deliveries: []
