name: Run

description: Integration - Run

inputs:
  dir:
    description: Working directory
    required: false
    default: .
  app:
    description: App
    required: false
  run:
    description: Run
    required: true

runs:
  using: node16
  main: action.js
