########
# Base #
########

FROM debian:bullseye-slim

ARG DEBIAN_FRONTEND="noninteractive"

ARG MANALA_USER_ID="1000"
ARG MANALA_GROUP_ID="1000"

ARG GOSU_VERSION="1.16"
ARG GOMPLATE_VERSION="3.11.4"

# The 'container' environment variable tells systemd that it's running inside a
# Docker container environment.
# It's also internally used for checking we're running inside a container.
ENV container="docker"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    # Backports
    echo "deb http://deb.debian.org/debian {{ include "os_release" "VERSION_CODENAME" }}-backports main" > /etc/apt/sources.list.d/backports.list \
    && apt-get --quiet update \
    && apt-get --quiet --yes --purge --autoremove upgrade \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        s6 \
        sudo \
        curl \
        ca-certificates \
        gnupg \
        libarchive-tools bzip2 \
        bash-completion \
        rsync \
        git \
        make \
        less \
        vim \
        socat \
    # Apt keyrings (debian < bookworm)
    && mkdir --verbose --parents /etc/apt/keyrings \
    # User
    && addgroup --gid ${MANALA_GROUP_ID} lazy \
    && adduser --home /home/lazy --shell /bin/bash --uid ${MANALA_USER_ID} --gecos lazy --ingroup lazy --disabled-password lazy \
    && mkdir --verbose --parents /run/user/${MANALA_USER_ID} && chown lazy:lazy /run/user/${MANALA_USER_ID} \
    && echo "lazy ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/lazy \
    # Gosu
    && curl -sSL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-{{ include "arch_map" (dict "amd64" "amd64" "arm64" "arm64") }}" \
        --output /usr/local/bin/gosu \
    && chmod +x /usr/local/bin/gosu \
    # Gomplate
    && curl -sSL "https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-{{ include "arch_map" (dict "amd64" "amd64" "arm64" "arm64") }}" \
        --output /usr/local/bin/gomplate \
    && chmod +x /usr/local/bin/gomplate \
    # Bash completion
    && mkdir --verbose --parents /etc/bash_completion.d \
    # Oh My Bash
    && git clone https://github.com/ohmybash/oh-my-bash.git /usr/local/share/oh-my-bash \
    # Clean
    && rm -rf /var/lib/apt/lists/*

##########
# System #
##########

{{ $apt := index .Vars.system "apt" -}}

RUN \
    apt-get --quiet update \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        unzip \
        {{- range $package := $apt.packages }}
        {{ $package }} \
        {{- end }}
    # Clean
    && rm -rf /var/lib/apt/lists/*

{{ if .Vars.system.docker -}}
# Docker
RUN \
    curl -sSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor --output /etc/apt/keyrings/docker.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ include "os_release" "VERSION_CODENAME" }} stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get --quiet update \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        docker-ce-cli \
    # Clean
    && rm -rf /var/lib/apt/lists/*

{{ end -}}

{{ $goss := .Vars.system.goss -}}
{{ if $goss.version -}}
# Goss
RUN \
    curl -sSL "https://github.com/goss-org/goss/releases/download/v{{ $goss.version }}/goss-linux-{{ include "arch_map" (dict "amd64" "amd64" "arm64" "arm64") }}" \
        --output /usr/local/bin/goss \
    && chmod +x /usr/local/bin/goss

{{ end -}}

# Nginx
{{ $nginx := .Vars.system.nginx -}}
RUN \
    curl -sSL http://nginx.org/keys/nginx_signing.key \
        | gpg --dearmor --output /etc/apt/keyrings/nginx.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nginx.gpg] http://nginx.org/packages/debian/ {{ include "os_release" "VERSION_CODENAME" }} nginx" > /etc/apt/sources.list.d/nginx.list \
    && printf "Package: nginx\n\
Pin: version {{ $nginx.version }}.*\n\
Pin-Priority: 1000\n\
" > /etc/apt/preferences.d/nginx \
    && apt-get --quiet update \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        nginx={{ $nginx.version }}.* \
    # Clean
    && rm -rf /var/lib/apt/lists/*

# Php
{{ $php := .Vars.system.php -}}
RUN \
    curl -sSL https://packages.sury.org/php/apt.gpg \
        --output /etc/apt/keyrings/sury.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/sury.gpg] https://packages.sury.org/php/ {{ include "os_release" "VERSION_CODENAME" }} main" > /etc/apt/sources.list.d/php.list \
    && apt-get --quiet update \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        php{{ $php.version }}-cli \
        php{{ $php.version }}-fpm \
        php{{ $php.version }}-opcache \
        php{{ $php.version }}-xdebug \
        # Symfony
        php{{ $php.version }}-intl \
        php{{ $php.version }}-curl \
        php{{ $php.version }}-mbstring \
        php{{ $php.version }}-xml \
        # Project
        {{- range $php.extensions }}
        php{{ $php.version }}-{{ . }} \
        {{- end }}
    && apt-get --quiet --yes --purge --autoremove upgrade \
    && phpdismod xdebug \
    && mkdir --verbose --parents /run/php \
    && update-alternatives --install /usr/sbin/php-fpm php-fpm /usr/sbin/php-fpm{{ $php.version }} 1 \
    && update-alternatives --install /etc/php/default php-config-default /etc/php/{{ $php.version }} 1 \
    # Composer
    && curl -sSL https://getcomposer.org/installer \
        | php -- --install-dir /usr/local/bin --filename composer \
    # Symfony
    && curl -sSL "https://github.com/symfony-cli/symfony-cli/releases/latest/download/symfony-cli_linux_{{ include "arch_map" (dict "amd64" "amd64" "arm64" "arm64") }}.tar.gz" \
        | bsdtar -xvf - -C /usr/local/bin symfony \
    # Clean
    && rm -rf /var/lib/apt/lists/*

{{ $nodejs := .Vars.system.nodejs -}}
{{ if $nodejs.version -}}
# Nodejs
RUN \
    curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key \
        | gpg --dearmor --output /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ $nodejs.version }}.x {{ include "os_release" "VERSION_CODENAME" }} main" > /etc/apt/sources.list.d/nodejs.list \
    && printf "Package: nodejs\n\
Pin: origin deb.nodesource.com\n\
Pin-Priority: 1000\n\
" > /etc/apt/preferences.d/nodejs \
    && curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg \
        | gpg --dearmor --output /etc/apt/keyrings/yarn.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get --quiet update \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        nodejs \
        yarn \
    # Clean
    && rm -rf /var/lib/apt/lists/*

{{ end -}}

{{ if .Vars.deploy.inventory -}}
# Ansistrano
RUN \
    apt-get --quiet update \
    && apt-get --quiet --yes --no-install-recommends --verbose-versions install \
        openssh-client \
        ansible \
    && ansible-galaxy install --roles-path /usr/share/ansible/roles \
        ansistrano.deploy,3.10.0 \
        ansistrano.rollback,3.1.0 \
    # Clean
    && rm -rf /var/lib/apt/lists/*

{{ end -}}

# Run
COPY docker/entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
