ARG STARSHIP_VERSION=0.51.0
ARG ANSIBLE_VERSION={{ .Vars.system.ansible.version | toString }}

########
# Base #
########

FROM debian:buster-slim as base

ARG STARSHIP_VERSION

# The 'container' environment variable tells systemd that it's running inside a
# Docker container environment.
# It's also internally used for checking we're running inside a container.
ENV container="docker"

RUN \
    apt-get update \
    && apt-get install --yes --no-install-recommends \
        bash-completion \
        apt-utils \
        gnupg \
        ca-certificates \
        sudo \
        curl \
        unzip \
        make \
        rsync \
        vim-tiny \
        less \
    # Bash completion
    && mkdir -p /etc/bash_completion.d \
    # User
    && adduser --disabled-password --gecos "" lazy \
    && echo "lazy ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/lazy \
    # Starship
    && curl --location https://github.com/starship/starship/releases/download/v${STARSHIP_VERSION}/starship-x86_64-unknown-linux-gnu.tar.gz \
        | tar zx -C /usr/local/bin \
    && echo "eval \"\$(starship init bash)\"" > /etc/profile.d/starship.sh

ENV STARSHIP_CONFIG="/etc/starship.toml"

COPY shell/starship.toml /etc/
COPY shell/message.sh /etc/profile.d/

WORKDIR /srv

###########
# Ansible #
###########

FROM base AS ansible

ARG ANSIBLE_VERSION

RUN \
    apt-get install --yes --no-install-recommends \
        python3 \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        python3-jinja2 \
        python3-yaml \
        python3-cryptography \
        python3-packaging \
        openssh-client sshpass \
    && pip3 install ansible==${ANSIBLE_VERSION}

CMD ["sleep", "infinity"]
