# Relative root dir ("."|".."|"../.."|…)
_ROOT_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT := $(if $(filter .,$(_ROOT_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_DIR := $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_ROOT_DIR))%,%,$(CURDIR)))

include $(_ROOT_DIR)/.manala/make/text.mk
include $(_ROOT_DIR)/.manala/make/help.mk
include $(_ROOT_DIR)/.manala/make/os.mk

###############
# Environment #
###############

ifneq ($(container),docker)

export COMPOSE_FILE         = $(_ROOT_DIR)/.manala/docker-compose.yaml
export COMPOSE_PROJECT_NAME = $(notdir $(CURDIR))

HELP += $(call help_section, Environment)

HELP += $(call help,up,        Create and start environment (BUILD))
up:
	$(call message,Create and start environment...)
	docker-compose up \
		$(if $(BUILD),--build --remove-orphans)

HELP += $(call help,clean,     Clean environment)
clean:
	$(call confirm,Please$(,) confirm environment cleaning)
	docker-compose down \
		--rmi all \
		--volumes \
		--remove-orphans

HELP += $(call help,sh,        Shell environment)
sh:
	docker-compose exec \
		--user lazy \
		ansible \
		bash -l

endif

###########
# Project #
###########

HELP += $(call help_section, Project)
