# Relative root dir ("."|".."|"../.."|…)
_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT = $(if $(filter .,$(_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_CURRENT_DIR = $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_DIR))%,%,$(CURDIR)))
# Relative cache dir ("./.manala/.cache"|"../.manala/.cache"|"../../.manala/.cache"|…)
_CACHE_DIR = $(shell dir=$(_DIR)/.manala/.cache ; mkdir -p $${dir} ; echo $${dir})

include $(_DIR)/.manala/make/text.mk
include $(_DIR)/.manala/make/help.mk
include $(_DIR)/.manala/make/os.mk
include $(_DIR)/.manala/make/try.mk
include $(_DIR)/.manala/make/git.mk
include $(_DIR)/.manala/make/semver.mk

###############
# Environment #
###############

include $(_DIR)/.manala/vagrant/make.mk

# Vagrant commands only available *OUTSIDE* vagrant environment
ifneq ($(container),vagrant)

export VAGRANT_CWD = $(_DIR)/.manala

HELP += $(call help_section, Environment)

# Setup commands only available *IN* root directory
ifdef _ROOT
HELP += $(call help,setup,               Setup environment)
setup:
	vagrant up --provision
	$(setup)
endif

HELP += $(call help,up,                  Start the environment)
up:
	vagrant up

HELP += $(call help,halt,                Stop the environment)
halt:
	vagrant halt

HELP += $(call help,reload,              Restart the environment)
reload:
	vagrant reload

HELP += $(call help,ssh,                 Connect to the environment via SSH)
ssh: export DIR = /srv/app/$(_CURRENT_DIR)
ssh:
	vagrant ssh

HELP += $(call help,destroy,             Stop and delete environment)
destroy:
	vagrant destroy

HELP += $(call help,provision,           Provision the environment (TAGS|DIFF|VERBOSE))
provision:
	vagrant provision --provision-with system

else

HELP += $(call help_section, Environment)

HELP += $(call help,provision,           Provision the environment (TAGS|DIFF|VERBOSE))
provision:
	$(call log, Install ansible galaxy collection)
	cd $(_DIR)/.manala/ansible \
		&& ansible-galaxy collection install \
			--requirements-file collections/requirements.yaml \
			--force
	$(call log, Run ansible playbook)
	cd $(_DIR)/.manala/ansible \
		&& ansible-playbook system.yaml \
			--inventory-file inventories \
			--limit development \
			--become \
			$(if $(TAGS),--tags $(TAGS)) \
			$(if $(VERBOSE),-vvv) \
			$(if $(DIFF),--check --diff)

endif

HELP += $(call help,provision.apt,       Provision the environment - Apt (DIFF|VERBOSE))
provision.apt: export TAGS = apt
provision.apt: provision

HELP += $(call help,provision.files,     Provision the environment - Files (DIFF|VERBOSE))
provision.files: export TAGS = files
provision.files: provision

HELP += $(call help,provision.nginx,     Provision the environment - Nginx (DIFF|VERBOSE))
provision.nginx: export TAGS = nginx
provision.nginx: provision

HELP += $(call help,provision.supervisor,Provision the environment - Supervisor (DIFF|VERBOSE))
provision.supervisor: export TAGS = supervisor
provision.supervisor: provision

HELP += $(call help,provision.php,       Provision the environment - Php (DIFF|VERBOSE))
provision.php: export TAGS = php
provision.php: provision

##########
# Docker #
##########

include $(_DIR)/.manala/docker/make.mk

# Docker commands only available *OUTSIDE* docker environment
ifneq ($(container),docker)

HELP += $(call help_section, Docker)

HELP += $(call help,docker,Run docker container)
docker:
	$(call docker_run)

endif

{{ if .Vars.releases -}}
############
# Releases #
############

HELP += $(call help_section, Releases)

{{ range $release := .Vars.releases }}

{{- if or (hasKey $release "release_tasks") (hasKey $release "release_add") (hasKey $release "release_removed") -}}
HELP += $(call help,release{{ include "release_target" $release }},Release {{ include "release_help" $release }})
release{{ include "release_target" $release }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
release{{ include "release_target" $release }}:
	$(call log, Run ansible playbook)
	ansible-playbook $(_DIR)/.manala/ansible/release.yaml \
		--inventory $(_DIR)/.manala/ansible/inventories/release.yaml \
		--limit {{ include "release_group" . }}

{{ end -}}

{{- if hasKey $release "deploy_hosts" -}}
HELP += $(call help,deploy{{ include "release_target" $release }},Deploy {{ include "release_help" $release }} (REF))
deploy{{ include "release_target" $release }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
deploy{{ include "release_target" $release }}:
	$(call log, Run ansible playbook)
	ansible-playbook $(_DIR)/.manala/ansible/deploy.yaml \
		--inventory $(_DIR)/.manala/ansible/inventories/deploy.yaml \
		--limit {{ include "release_group" $release }} \
		$(if $(REF),--extra-vars '{"deploy_strategy_git_ref": "$(REF)"}')

{{ end -}}

{{ end }}

{{- end -}}
