[hostname]
ssh_only = false
trim_at = ""

[username]
show_always = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[php]
disabled = true

[nodejs]
disabled = true
