include \
  .manala/make/make.text.mk \
  .manala/make/make.help.mk \
  .manala/make/make.os.mk \
  .manala/make/make.try.mk \
  .manala/make/make.git.mk \
  .manala/make/make.semver.mk

##########
# Docker #
##########

include .manala/make/make.docker.mk

ifneq ($(container),docker)
HELP += $(call help_section,Docker)

HELP += $(call help,docker,Run docker container)
docker:
	$(call docker_run)

HELP += \n
endif

{{ if .Vars.releases -}}
############
# Releases #
############

HELP += $(call help_section,Releases)

{{ range $release := .Vars.releases -}}
HELP += $(call help,release{{ include "release_target" $release }},Release {{ include "release_help" $release }})
release{{ include "release_target" $release }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
release{{ include "release_target" $release }}:
		ansible-playbook .manala/ansible/release.yaml \
			--inventory .manala/ansible/release.inventory.yaml \
			--limit {{ include "release_group" $release }}

{{ if hasKey $release "deploy_hosts" -}}
HELP += $(call help,deploy{{ include "release_target" $release }},Deploy {{ include "release_help" $release }})
deploy{{ include "release_target" $release }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
deploy{{ include "release_target" $release }}:
	ansible-playbook .manala/ansible/deploy.yaml \
		--inventory .manala/ansible/deploy.inventory.yaml \
		--limit {{ include "release_group" $release }}

{{ end -}}

{{ end -}}

HELP += \n

{{ end -}}

{{ if .Vars.deliveries -}}
{{ $deliveries := .Vars.deliveries -}}

##############
# Deliveries #
##############

HELP += $(call help_section,Deliveries)

{{ range $delivery := $deliveries -}}

{{ $delivery_target := include "delivery_target" $delivery -}}
{{ $delivery_help := include "delivery_help" $delivery -}}
{{ $delivery_group := include "delivery_group" $delivery -}}

{{ if hasKey $delivery "release" -}}
HELP += $(call help,release{{ $delivery_target }},Release {{ $delivery_help }})
release{{ $delivery_target }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
release{{ $delivery_target }}:
		ansible-playbook .manala/ansible/release.yaml \
			--inventory .manala/ansible/release.inventory.yaml \
			--limit {{ $delivery_group }}

{{ end -}}

{{ if hasKey $delivery "deploy" -}}
HELP += $(call help,deploy{{ $delivery_target }},Deploy {{ $delivery_help }})
deploy{{ $delivery_target }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
deploy{{ $delivery_target }}:
	ansible-playbook .manala/ansible/deploy.yaml \
		--inventory .manala/ansible/deploy.inventory.yaml \
		--limit {{ $delivery_group }}

{{ end -}}

{{ end -}}

HELP += \n

{{ end -}}

#######
# App #
#######

HELP += $(call help_section,App)
