include \
  .manala/make/make.text.mk \
  .manala/make/make.help.mk \
  .manala/make/make.os.mk \
  .manala/make/make.try.mk \
  .manala/make/make.git.mk \
  .manala/make/make.semver.mk

##########
# Docker #
##########

include .manala/make/make.docker.mk

ifneq ($(container),docker)
HELP += $(call help_section, Docker)

HELP += $(call help,docker,Run docker container)
docker:
	$(call docker_run)

endif

{{ if .Vars.releases -}}
############
# Releases #
############

HELP += $(call help_section, Releases)

{{ range $release := .Vars.releases -}}
HELP += $(call help,release{{ include "release_target" $release }},Release {{ include "release_help" $release }})
release{{ include "release_target" $release }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
release{{ include "release_target" $release }}:
		ansible-playbook .manala/ansible/release.yaml \
			--inventory .manala/ansible/release.inventory.yaml \
			--limit {{ include "release_group" $release }}

{{ if hasKey $release "deploy_hosts" -}}
HELP += $(call help,deploy{{ include "release_target" $release }},Deploy {{ include "release_help" $release }} (REF))
deploy{{ include "release_target" $release }}: SHELL := $(or $(DOCKER_SHELL),$(SHELL))
deploy{{ include "release_target" $release }}:
	ansible-playbook .manala/ansible/deploy.yaml \
		--inventory .manala/ansible/deploy.inventory.yaml \
		--limit {{ include "release_group" $release }} \
		$(if $(REF),--extra-vars '{"deploy_strategy_git_ref": "$(REF)"}')

{{ end -}}

{{ end -}}

{{ end -}}
#######
# App #
#######

HELP += $(call help_section, App)
