services:

    #######
    # App #
    #######

    app:
        volumes:
            - ${MANALA_DOCKER_SOCK}:/run/docker.sock
        environment:
            DOCKER_HOST: unix:///run/docker-bridge.sock
