services:

    #######
    # App #
    #######

    app:
        build:
            args:
                MANALA_INIT: systemd
        cgroup: host
        cap_add:
            - SYS_ADMIN
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
        tmpfs:
            - /run
