services:

    #######
    # App #
    #######

    app:
        build:
            args:
                MANALA_INIT: systemd
        cgroup: host
        tty: true
        tmpfs:
            - /run
            - /run/lock
        security_opt:
            - apparmor=unconfined
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:rw
