name: Run

description: System - Run

inputs:
  dir:
    description: Working directory
    required: false
    default: .
  docker_dir:
    description: Docker working directory
    required: false
  docker_env:
    description: Docker env
    required: false
  run:
    description: Run
    required: true

runs:
  using: node16
  main: action.js
