name: Release

description: Deliveries - Release

inputs:
  app:
    description: App
    required: false
  tier:
    description: Tier
    required: true

runs:
  using: composite
  steps:

    - name: >
        Release
        ${{ inputs.app && format('{0}', inputs.app) || '' }}@${{ inputs.tier }}
      uses: ./.manala/github/integration/run
      with:
        dir: deliveries/${{ inputs.app && format('{0}/', inputs.app) || '' }}${{ inputs.tier }}
        run: |
          make release${{ inputs.app && format('.{0}', inputs.app) || '' }}@${{ inputs.tier }} \
            AUTHOR="manala-ci-releaser <${{ github.actor }}+github@manala.io>"
