manala:
    description: Ansible environment, opiniated, docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/make
      - .manala/shell
      - .manala/docker-compose.yaml.tmpl
      - .manala/Dockerfile.tmpl
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    # @schema {"items": {"type": "string"}}
    volumes: []
    ansible:
        # @schema {"enum": ["3.1.0", "2.10.7", "2.10.4"]}
        # @option {"label": "Ansible version"}
        version: ~
