manala:
    description: Ansible administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/etc
      - .manala/github
      - .manala/gitlab
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1, "pattern": "^[a-z0-9][a-z0-9_-]*$"}
    # @option {"label": "Project name"}
    name: ~
    # @schema {"type": ["null", "string"]}
    help: ~

##########
# System #
##########

system:
    dir: ~
    locale: C.UTF-8
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {
    #     "type": ["string", "array"],
    #     "items": {"oneOf": [
    #         {"type": "string"},
    #         {
    #             "type": "object",
    #             "properties": {
    #                  "path": {"type": "string"},
    #                  "required": {"type": "boolean"}
    #             },
    #             "required": ["path"],
    #             "additionalProperties": false
    #         }
    #     ]}
    # }
    env_file: []
    # @schema {"items": {"type": "string"}}
    mount: []
    # @schema {"items": {"type": "string"}}
    tmpfs: []
    starship:
        # @schema {"type": ["null", "string"]}
        config: ~
    docker: false
    apt:
        # @schema {"items": {"type": "string"}}
        packages: []
    git:
        # @schema {"type": ["null", "string"]}
        config: ~
    ssh:
        # @schema {"type": ["null", "string"]}
        config: ~
    ansible:
        # @schema {"enum": ["2.19.2", "2.18.9", "2.17.14", "2.16.14"]}
        # @option {"label": "Ansible version"}
        version: ~
        # @schema {"type": ["null", "string"]}
        config: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    ansible-lint:
        # @schema {"enum": [null, "25.9.1", "25.7.0", "24.9.2", "24.7.0", "24.6.1", "24.5.0"]}
        # @option {"label": "Ansible-lint version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    molecule:
        # @schema {"enum": [null, "25.9.0", "25.7.0", "24.9.0", "24.8.0", "24.7.0", "24.6.1"]}
        # @option {"label": "Molecule version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    terraform:
        # @schema {"enum": [null, "1.13.3", "1.12.2", "1.11.4", "1.10.5", "1.9.8"]}
        # @option {"label": "Terraform version"}
        version: ~
    gcloud:
        # @schema {"enum": [null, "541.0.0"]}
        # @option {"label": "Google Cloud cli version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        components: []
