manala:
    description: Ansible administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/etc
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~
    # @schema {"type": ["null", "string"]}
    help: ~

##########
# System #
##########

system:
    dir: ~
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: []
    # @schema {"items": {"type": "string"}}
    mount: []
    docker: false
    goss:
        # @schema {"enum": [null, "0.3.21"]}
        version: ~
    ssh:
        # @schema {"type": ["null", "string"]}
        config: ~
    ansible:
        # @schema {"enum": ["2.14.2", "2.13.7", "2.12.10"]}
        # @option {"label": "Ansible version"}
        version: ~
        # @schema {"type": ["null", "string"]}
        config: ~
    ansible-lint:
        # @schema {"enum": [null, "6.12.1", "6.11.0", "6.10.2"]}
        # @option {"label": "Ansible-lint version"}
        version: ~
    molecule:
        # @schema {"enum": [null, "4.0.4"]}
        # @option {"label": "Molecule version"}
        version: ~
        plugins:
            # @schema {"enum": [null, "23.0.0"]}
            # @option {"label": "Molecule Plugins version"}
            version: ~
            azure: false
            docker: false
            gce: false
