manala:
    description: Ansible administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/etc
      - .manala/github
      - .manala/gitlab
      - .manala/make
      - .manala/services
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1, "pattern": "^[a-z0-9][a-z0-9_-]*$"}
    # @option {"label": "Project name"}
    name: ~
    # @schema {"type": ["null", "string"]}
    help: ~

##########
# System #
##########

system:
    dir: ~
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: []
    # @schema {"items": {"type": "string"}}
    mount: []
    docker: false
    goss:
        # @schema {"enum": [null, "0.4.4", "0.3.23"]}
        version: ~
    apt:
        # @schema {"items": {"type": "string"}}
        packages: []
    git:
        # @schema {"type": ["null", "string"]}
        config: ~
    ssh:
        # @schema {"type": ["null", "string"]}
        config: ~
    ansible:
        # @schema {"enum": ["2.16.2", "2.15.8", "2.14.13"]}
        # @option {"label": "Ansible version"}
        version: ~
        # @schema {"type": ["null", "string"]}
        config: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    ansible-lint:
        # @schema {"enum": [null, "6.22.2", "6.14.6", "6.13.1"]}
        # @option {"label": "Ansible-lint version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    molecule:
        # @schema {"enum": [null, "6.0.3", "5.1.0", "5.0.1"]}
        # @option {"label": "Molecule version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    terraform:
        # @schema {"enum": [null, "1.7.1", "1.6.6", "1.5.7"]}
        # @option {"label": "Terraform version"}
        version: ~
