manala:
    description: Ansible administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/make
      - .manala/templates
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    dir: ~
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: ""
    # @schema {"items": {"type": "string"}}
    mount: []
    docker: false
    ansible:
        # @schema {"enum": ["2.11.12"]}
        # @option {"label": "Ansible version"}
        version: ~
    ansible_lint:
        # @schema {"enum": [null, "6.3.0"]}
        # @option {"label": "Ansible Lint version"}
        version: ~
    molecule:
        # @schema {"enum": [null, "4.0.0"]}
        # @option {"label": "Molecule version"}
        version: ~
        docker:
          # @schema {"enum": [null, "1.1.0"]}
          # @option {"label": "Molecule Docker version"}
          version: ~
