manala:
    description: Ansible administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/make
      - .manala/templates
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: ""
    # @schema {"items": {"type": "string"}}
    mount: []
    ansible:
        # @schema {"enum": ["2.11.5"]}
        # @option {"label": "Ansible version"}
        version: ~
