---

collections:
  - ansible.posix
  - community.crypto
  - community.docker
  - community.general
  - community.mongodb
  - community.mysql
  - gluster.gluster
  # !!! Not Ready !!!
  #- manala.roles
  - name: https://github.com/manala/ansible-roles.git
    type: git
    version: apt/deb822
