manala:
    description: Symfony environment, opiniated, docker based, for lazy people
    sync:
      - .manala/ansistrano
      - .manala/docker
      - .manala/make
      - .manala/mariadb
      - .manala/nginx
      - .manala/php
      - .manala/starship
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/docker-compose.yaml.tmpl
      - .manala/Dockerfile.tmpl
      - .manala/Makefile.tmpl
      - .manala.yaml.tmpl.dist
      - Makefile.dist
      - README.md .manala/README.md

#######
# App #
#######

# @option {"label": "App name"}
# @schema {"type": "string", "pattern": "^[-a-z]+$"}
app: ~

##########
# System #
##########

system:
    # @schema {"enum": [8000, 9000, 10000]}
    ports: 8000
    nginx:
        # @option {"label": "Nginx version"}
        # @schema {"enum": [1.18]}
        version: ~
    php:
        # @option {"label": "Php version"}
        # @schema {"enum": [7.4]}
        version: ~
    nodejs:
        # @option {"label": "Nodejs version"}
        # @schema {"enum": [null, 12]}
        version: ~
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.4]}
        version: ~

##########
# Deploy #
##########

deploy:
    # @schema {"items": {"type": "object"}}
    inventory: {}
    # @schema {"items": {"type": "string"}}
    excludes: []
    # @schema {"items": {"type": "string"}}
    shared_paths: []
    # @schema {"items": {"type": "string"}}
    shared_files: []
    hooks:
      # @schema {"items": {"type": "object"}}
      before_symlink: []
