manala:
    description: Symfony development environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/ansistrano
      - .manala/docker
      - .manala/make
      - .manala/templates
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: ""
    # @schema {"items": {"type": "string"}}
    mount: []
    nginx:
        # @option {"label": "Nginx version"}
        # @schema {"enum": ["1.20"]}
        version: ~
        # @schema {"type": "integer", "exclusiveMinimum": 1024, "maximum": 65535}
        port: 8000
    php:
        # @option {"label": "Php version"}
        # @schema {"enum": [8.1, "8.0", 7.4]}
        version: ~
        # @schema {"items": {"type": "string"}}
        extensions: []
    nodejs:
        # @option {"label": "Nodejs version"}
        # @schema {"enum": [null, 16, 14, 12]}
        version: ~
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.5, 10.4]}
        version: ~
        # @schema {"type": "integer", "exclusiveMinimum": 1024, "maximum": 65535}
        port: 8306
    phpmyadmin:
        # @option {"label": "PhpMyAdmin version"}
        # @schema {"enum": [null, 5.1]}
        version: ~
        # @schema {"type": "integer", "exclusiveMinimum": 1024, "maximum": 65535}
        port: 8300
    maildev:
        # @option {"label": "MailDev version"}
        # @schema {"enum": [null, "2.0.0-beta3"]}
        version: ~
        # @schema {"type": "integer", "exclusiveMinimum": 1024, "maximum": 65535}
        port: 8025
    network:
      # @schema {"items": {"type": "string"}}
      ports: []

##########
# Deploy #
##########

deploy:
    # @schema {"items": {"type": "object"}}
    inventory: {}
    # @schema {"items": {"type": "string"}}
    includes: []
    # @schema {"items": {"type": "string"}}
    excludes: []
    # @schema {"items": {"type": "string"}}
    shared_paths: []
    # @schema {"items": {"type": "string"}}
    shared_files: []
    hooks:
      # @schema {"items": {"type": "object"}}
      before_symlink: []
