# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
disabled = false
ssh_only = false
trim_at = ""

[username]
disabled = false
show_always = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[php]
disabled = true
