FROM golang:alpine3.9 AS provider-openstack

RUN apk add --no-cache git \
	&& go get -d -v github.com/terraform-providers/terraform-provider-openstack \
	&& git -C ./src/github.com/terraform-providers/terraform-provider-openstack checkout v1.24.0 \
	&& go install ./src/github.com/terraform-providers/terraform-provider-openstack

FROM golang:alpine3.9 AS provider-gandi

RUN apk add --no-cache git make bash \
	&& git clone https://github.com/tiramiseb/terraform-provider-gandi.git \
	&& git -C ./terraform-provider-gandi checkout v1.1.1 \
	&& cd terraform-provider-gandi/ && make -f GNUmakefile build

FROM hashicorp/terraform:{{ .Vars.system.terraform.version }}

COPY --from=provider-openstack /go/bin/terraform-provider-openstack /bin
COPY --from=provider-gandi /go/bin/terraform-provider-gandi /bin

RUN apk add --no-cache zsh
RUN sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

COPY etc/terraform/zshrc /root/.zshrc
RUN rm -rf /root/.zcompdump*

WORKDIR /srv
