FROM golang:alpine3.9 AS alt-galaxy

RUN apk add --no-cache \
		git \
	&& go get -v github.com/gantsign/alt-galaxy

FROM alpine:3.9

COPY --from=alt-galaxy /go/bin/alt-galaxy /usr/local/bin

RUN apk add --no-cache \
  bash \
  ca-certificates \
  openssh-client \
  make \
  python3 \
  && apk --update add --virtual build-deps python3-dev libffi-dev openssl-dev build-base \
  && pip3 install --upgrade pip setuptools \
  && pip3 install ansible=={{ .Vars.system.ansible.version }} \
  && pip3 install netaddr==0.7.19 \
  && pip3 install boto==2.49.0 \
  && pip3 install boto3==1.9.230 \
  && pip3 install openstacksdk==0.35.0 \
  && apk del build-deps \
  && rm -rf /var/cache/apk/*

# Apply some patches
ADD patches/ansible/{{ .Vars.system.ansible.version }} /patch
RUN cd /usr/lib/python3.6/site-packages/ansible && /bin/bash -c 'for f in /patch/*.patch; do patch -p1 < $f; done;'

# Make some useful symlinks that are expected to exist
RUN cd /usr/bin \
  && ln -s /usr/bin/python3 python \
  && ln -s /usr/bin/pydoc3 pydoc

WORKDIR /srv

ENV ANSIBLE_GATHERING smart
ENV ANSIBLE_RETRY_FILES_ENABLED false
ENV ANSIBLE_SSH_PIPELINING true
ENV PATH /ansible/bin:$PATH
ENV PYTHONPATH /ansible/lib

CMD ["tail", "-f", "/dev/null"]
