ARG STARSHIP_VERSION=0.51.0
ARG KUBECTL_VERSION={{ .Vars.system.kubectl.version | toString }}
{{- if .Vars.system.helm.version }}
ARG HELM_VERSION={{ .Vars.system.helm.version | toString }}
{{- end }}
{{- if .Vars.system.k9s.version }}
ARG K9S_VERSION={{ .Vars.system.k9s.version | toString }}
{{- end }}
{{- if .Vars.system.stern.version }}
ARG STERN_VERSION={{ .Vars.system.stern.version | toString }}
{{- end }}
{{- if .Vars.system.kubespy.version }}
ARG KUBESPY_VERSION={{ .Vars.system.kubespy.version | toString }}
{{- end }}
{{- if .Vars.system.kubebox.version }}
ARG KUBEBOX_VERSION={{ .Vars.system.kubebox.version | toString }}
{{- end }}
{{- if .Vars.system.kube_prompt.version }}
ARG KUBE_PROMPT_VERSION={{ .Vars.system.kube_prompt.version | toString }}
{{- end }}
{{- if .Vars.system.popeye.version }}
ARG POPEYE_VERSION={{ .Vars.system.popeye.version | toString }}
{{- end }}

########
# Base #
########

FROM debian:buster-slim as base

ARG STARSHIP_VERSION

# The 'container' environment variable tells systemd that it's running inside a
# Docker container environment.
# It's also internally used for checking we're running inside a container.
ENV container="docker"

RUN \
    apt-get update \
    && apt-get install --yes --no-install-recommends \
        bash-completion \
        apt-utils \
        gnupg \
        ca-certificates \
        sudo \
        curl \
        unzip \
        make \
        rsync \
        vim-tiny \
        less \
        bsdtar \
    # Bash completion
    && mkdir -p /etc/bash_completion.d \
    # User
    && adduser --disabled-password --gecos "" lazy \
    && echo "lazy ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/lazy \
    # Starship
    && curl --location https://github.com/starship/starship/releases/download/v${STARSHIP_VERSION}/starship-x86_64-unknown-linux-gnu.tar.gz \
        | bsdtar -xf - -C /usr/local/bin \
    && echo "eval \"\$(starship init bash)\"" > /etc/profile.d/starship.sh

ENV STARSHIP_CONFIG="/etc/starship.toml"

COPY shell/starship.toml /etc/
COPY shell/message.sh /etc/profile.d/

##############
# Kubernetes #
##############

FROM base AS kubernetes

# Kubectl
ARG KUBECTL_VERSION
RUN \
    curl --location https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
        --output /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    # Bash completion
    && kubectl completion bash > /etc/bash_completion.d/kubectl

{{- if .Vars.system.helm.version }}

# Helm
ARG HELM_VERSION
RUN \
    curl --location https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
        | bsdtar -xf - --strip-components=1 -C /usr/local/bin linux-amd64/helm \
    # Bash completion
    && helm completion bash > /etc/bash_completion.d/helm
{{- end }}

{{- if .Vars.system.k9s.version }}

# K9s
ARG K9S_VERSION
RUN \
    curl --location https://github.com/derailed/k9s/releases/download/v${K9S_VERSION}/k9s_Linux_x86_64.tar.gz \
        | bsdtar -xf - -C /usr/local/bin k9s
{{- end }}

{{- if .Vars.system.stern.version }}

# Stern
ARG STERN_VERSION
RUN \
    curl --location https://github.com/stern/stern/releases/download/v${STERN_VERSION}/stern_${STERN_VERSION}_linux_amd64.tar.gz \
        | bsdtar -xf - --strip-components=1 -C /usr/local/bin stern_${STERN_VERSION}_linux_amd64/stern \
    # Bash completion
    && stern --completion=bash > /etc/bash_completion.d/stern
{{- end }}

{{- if .Vars.system.kubespy.version }}

# Kubespy
ARG KUBESPY_VERSION
RUN \
    curl --location https://github.com/pulumi/kubespy/releases/download/v${KUBESPY_VERSION}/kubespy-v${KUBESPY_VERSION}-linux-amd64.tar.gz \
        | bsdtar -xf - -C /usr/local/bin kubespy
{{- end }}

{{- if .Vars.system.kubebox.version }}

# Kubebox
ARG KUBEBOX_VERSION
RUN \
    curl --location https://github.com/astefanutti/kubebox/releases/download/v${KUBEBOX_VERSION}/kubebox-linux \
        --output /usr/local/bin/kubebox \
    && chmod +x /usr/local/bin/kubebox
{{- end }}

{{- if .Vars.system.kube_prompt.version }}

# Kube Prompt
ARG KUBE_PROMPT_VERSION
RUN \
    curl --location https://github.com/c-bata/kube-prompt/releases/download/v${KUBE_PROMPT_VERSION}/kube-prompt_v${KUBE_PROMPT_VERSION}_linux_amd64.zip \
        | bsdtar -xf - -C /usr/local/bin \
    && chmod +x /usr/local/bin/kube-prompt
{{- end }}

{{- if .Vars.system.popeye.version }}

# Popeye
ARG POPEYE_VERSION
RUN \
    curl --location https://github.com/derailed/popeye/releases/download/v${POPEYE_VERSION}/popeye_Linux_x86_64.tar.gz \
        | bsdtar -xf - -C /usr/local/bin popeye
{{- end }}
