ARG STARSHIP_VERSION=0.51.0
ARG KUBECTL_VERSION={{ .Vars.system.kubectl.version | toString }}
{{- if .Vars.system.helm.version }}
ARG HELM_VERSION={{ .Vars.system.helm.version | toString }}
{{- end }}

########
# Base #
########

FROM debian:buster-slim as base

ARG STARSHIP_VERSION

# The 'container' environment variable tells systemd that it's running inside a
# Docker container environment.
# It's also internally used for checking we're running inside a container.
ENV container="docker"

RUN \
    apt-get update \
    && apt-get install --yes --no-install-recommends \
        bash-completion \
        apt-utils \
        gnupg \
        ca-certificates \
        sudo \
        curl \
        unzip \
        make \
        rsync \
        vim-tiny \
        less \
    # Bash completion
    && mkdir -p /etc/bash_completion.d \
    # User
    && adduser --disabled-password --gecos "" lazy \
    && echo "lazy ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/lazy \
    # Starship
    && curl --location https://github.com/starship/starship/releases/download/v${STARSHIP_VERSION}/starship-x86_64-unknown-linux-gnu.tar.gz \
        | tar zx -C /usr/local/bin \
    && echo "eval \"\$(starship init bash)\"" > /etc/profile.d/starship.sh

ENV STARSHIP_CONFIG="/etc/starship.toml"

COPY shell/starship.toml /etc/
COPY shell/message.sh /etc/profile.d/

##############
# Kubernetes #
##############

FROM base AS kubernetes

# Kubectl
ARG KUBECTL_VERSION
RUN \
    curl --location https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
        --output /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    # Bash completion
    && kubectl completion bash > /etc/bash_completion.d/kubectl

{{- if .Vars.system.helm.version }}

# Helm
ARG HELM_VERSION
RUN \
    curl --location https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
        | tar zx --strip-components=1 -C /usr/local/bin linux-amd64/helm \
    # Bash completion
    && helm completion bash > /etc/bash_completion.d/helm
{{- end }}
