# Relative root dir ("."|".."|"../.."|…)
_ROOT_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT := $(if $(filter .,$(_ROOT_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_DIR := $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_ROOT_DIR))%,%,$(CURDIR)))

include $(_ROOT_DIR)/.manala/make/text.mk
include $(_ROOT_DIR)/.manala/make/help.mk
include $(_ROOT_DIR)/.manala/make/os.mk
include $(_ROOT_DIR)/.manala/make/docker_compose.mk
include $(_ROOT_DIR)/.manala/make/kubectl.mk
{{- if .Vars.system.helm.version }}
include $(_ROOT_DIR)/.manala/make/helm.mk
{{- end }}
{{- if .Vars.system.k9s.version }}
include $(_ROOT_DIR)/.manala/make/k9s.mk
{{- end }}

###############
# Environment #
###############

ifneq ($(container),docker)

export _DOCKER_WORKDIR := $(realpath $(_ROOT_DIR))

_DOCKER_COMPOSE_FILE := $(_ROOT_DIR)/.manala/docker-compose.yaml
_DOCKER_PROJECT_NAME := {{ .Vars.project.name }}
{{- if .Vars.system.mount }}
_DOCKER_VOLUMES      := {{ .Vars.system.mount | join " " }}
{{- end }}
_DOCKER_SERVICE      := kubernetes

HELP += $(call help_section, Environment)

HELP += $(call help,sh,   Shell environment)
sh:
	$(docker_compose_run) bash -l

HELP += $(call help,clean,Clean environment)
clean:
	$(call confirm,Confirm environment cleaning)
	$(docker_compose_clean)

endif

###########
# Project #
###########

HELP += $(call help_section, Project)
