version: "3.7"

services:

  ##########
  # System #
  ##########

  system:
    volumes:
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    environment:
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
      # Php - XDebug
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal
