# Relative root dir ("."|".."|"../.."|…)
_ROOT_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT := $(if $(filter .,$(_ROOT_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_DIR := $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_ROOT_DIR))%,%,$(CURDIR)))

include $(_ROOT_DIR)/.manala/make/text.mk
include $(_ROOT_DIR)/.manala/make/help.mk
include $(_ROOT_DIR)/.manala/make/os.mk

###############
# Environment #
###############

ifneq ($(container),docker)

export COMPOSE_FILE         = $(_ROOT_DIR)/.manala/docker-compose.yaml
export COMPOSE_PROJECT_NAME = {{ .Vars.app }}

HELP += $(call help_section, Environment)

HELP += $(call help,up,        Create and start environment (BUILD))
up:
	$(call message,Create and start environment...)
	mkdir -p $(_ROOT_DIR)/.manala/.cache
	OS=$(OS) \
	$(if $(OS_DARWIN),SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock) \
		docker-compose up \
			$(if $(BUILD),--build --remove-orphans)

HELP += $(call help,clean,     Clean environment)
clean:
	$(call confirm,Please$(,) confirm environment cleaning)
	OS=$(OS) \
		docker-compose down \
			--rmi all \
			--volumes \
			--remove-orphans

HELP += $(call help,sh,        Shell environment)
sh:
	docker-compose exec \
		--user app \
		app \
		bash -l

HELP += $(call help,sh.nginx,  Shell environment - Nginx)
sh.nginx:
	docker-compose exec \
		nginx \
		bash

{{- if .Vars.system.mariadb.version }}

HELP += $(call help,sh.mariadb,Shell environment - MariaDB)
sh.mariadb:
	docker-compose exec \
		mariadb \
		bash

{{- end }}

endif

{{- if .Vars.deploy.inventory }}

##########
# Deploy #
##########

HELP += $(call help_section, Deploy)

{{- range $group, $hosts := .Vars.deploy.inventory }}
{{- range $host, $vars := $hosts }}

HELP += $(call help,ssh@{{ $host }}, Ssh to {{ $host }})
ssh@{{ $host }}:
	ssh {{ $vars.user }}@{{ $vars.host }}

{{- end }}
{{- end }}

{{- range $group, $hosts := .Vars.deploy.inventory }}

HELP += $(call help,deploy@{{ $group }}, Deploy to {{ $group }})
deploy@{{ $group }}:
	ansible-playbook $(_ROOT_DIR)/.manala/ansistrano/playbook.yaml \
		--inventory $(_ROOT_DIR)/.manala/ansistrano/inventory.yaml \
		--limit {{ $group}}

{{- end }}

{{- end }}

#######
# App #
#######

HELP += $(call help_section, App)
