manala:
    description: Kubernetes cluster administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/etc
      - .manala/github
      - .manala/gitlab
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1, "pattern": "^[a-z0-9][a-z0-9_-]*$"}
    # @option {"label": "Project name"}
    name: ~
    # @schema {"type": ["null", "string"]}
    help: ~

##########
# System #
##########

system:
    dir: ~
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {
    #     "type": ["string", "array"],
    #     "items": {"oneOf": [
    #         {"type": "string"},
    #         {
    #             "type": "object",
    #             "properties": {
    #                  "path": {"type": "string"},
    #                  "required": {"type": "boolean"}
    #             },
    #             "required": ["path"],
    #             "additionalProperties": false
    #         }
    #     ]}
    # }
    env_file: []
    # @schema {"items": {"type": "string"}}
    mount: []
    docker: false
    goss:
        # @schema {"enum": [null, "0.4.8", "0.3.23"]}
        version: ~
    apt:
        # @schema {"items": {"type": "string"}}
        packages: []
    git:
        # @schema {"type": ["null", "string"]}
        config: ~
    kubectl:
        # @schema {"enum": ["1.31.1", "1.30.5", "1.29.9", "1.28.14", "1.27.16", "1.26.15", "1.25.16", "1.24.17", "1.23.17"]}
        # @option {"label": "Kubectl version"}
        version: ~
    helm:
        # @schema {"enum": [null, "3.16.1", "3.15.4", "3.14.4", "3.13.3"]}
        # @option {"label": "Helm version"}
        version: ~
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "url": {"type": "string"},
        #             "path": {"type": "string"},
        #             "version": {"type": "string"}
        #         },
        #         "oneOf": [
        #             {"required": ["url"]},
        #             {"required": ["path"]}
        #         ]
        #     }
        # }
        plugins: []
    helmfile:
        # @schema {"enum": [null, "0.168.0"]}
        # @option {"label": "Helmfile version"}
        version: ~
    k9s:
        # @schema {"enum": [null, "0.32.5"]}
        # @option {"label": "K9s version"}
        version: ~
    stern:
        # @schema {"enum": [null, "1.30.0"]}
        # @option {"label": "Stern version"}
        version: ~
    popeye:
        # @schema {"enum": [null, "0.21.5"]}
        # @option {"label": "Popeye version"}
        version: ~
    vault:
        # @schema {"enum": [null, "1.17.5", "1.16.3", "1.15.6", "1.14.10"]}
        # @option {"label": "Vault version"}
        version: ~
    rclone:
        # @schema {"enum": [null, "1.68.0"]}
        # @option {"label": "Rclone version"}
        version: ~
    openstack:
        # @schema {"enum": [null, "7.1.2", "7.0.0", "6.6.1"]}
        # @option {"label": "Openstack client version"}
        version: ~
    swift:
        # @schema {"enum": [null, "4.6.0"]}
        # @option {"label": "Swift client version"}
        version: ~
        keystone:
            # @schema {"enum": [null, "5.4.0"]}
            # @option {"label": "Swift keystone client version"}
            version: ~
    scw:
        # @schema {"enum": [null, "2.34.0"]}
        # @option {"label": "Scaleway cli version"}
        version: ~
    sops:
        # @schema {"enum": [null, "3.9.0"]}
        # @option {"label": "Sops version"}
        version: ~
    aws:
        # @schema {"enum": [null, "2.17.57"]}
        # @option {"label": "AWS cli version"}
        version: ~
    gcloud:
        # @schema {"enum": [null, "493.0.0"]}
        # @option {"label": "Google Cloud cli version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        components: []
    age:
        # @schema {"enum": [null, "1.2.0"]}
        # @option {"label": "Age version"}
        version: ~
    argocd:
        # @schema {"enum": [null, "2.12.3"]}
        # @option {"label": "ArgoCD version"}
        version: ~
