manala:
    description: Kubernetes cluster administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/make
      - .manala/templates
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/docker-compose.darwin.yaml
      - .manala/docker-compose.linux.yaml
      - .manala/docker-compose.windows.yaml
      - .manala/docker-compose.yaml.tmpl
      - .manala/Dockerfile.tmpl
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"items": {"type": "string"}}
    mount: []
    kubectl:
        # @schema {"enum": ["1.21.4", "1.20.10", "1.19.14", "1.18.20"]}
        # @option {"label": "Kubectl version"}
        version: ~
    helm:
        # @schema {"enum": [null, "3.6.3"]}
        # @option {"label": "Helm version"}
        version: ~
    k9s:
        # @schema {"enum": [null, "0.24.15"]}
        # @option {"label": "K9s version"}
        version: ~
    stern:
        # @schema {"enum": [null, "1.20.1"]}
        # @option {"label": "Stern version"}
        version: ~
    kubespy:
        # @schema {"enum": [null, "0.6.0"]}
        # @option {"label": "Kubespy version"}
        version: ~
    kubebox:
        # @schema {"enum": [null, "0.9.0"]}
        # @option {"label": "Kubebox version"}
        version: ~
    kube_prompt:
        # @schema {"enum": [null, "1.0.11"]}
        # @option {"label": "Kube Prompt version"}
        version: ~
    popeye:
        # @schema {"enum": [null, "0.9.7"]}
        # @option {"label": "Popeye version"}
        version: ~
    knsk:
        # @schema {"enum": [null, "1.0"]}
        # @option {"label": "Kubernetes namespace killer version"}
        version: ~
    vault:
        # @schema {"enum": [null, "1.8.2"]}
        # @option {"label": "Vault version"}
        version: ~
    rclone:
        # @schema {"enum": [null, "1.56.0"]}
        # @option {"label": "Rclone version"}
      version: ~
    openstack:
        # @schema {"enum": [null, "5.6.0"]}
        # @option {"label": "Openstack client version"}
      version: ~
    swift:
        # @schema {"enum": [null, "3.12.0"]}
        # @option {"label": "Swift client version"}
      version: ~
      keystone:
        # @schema {"enum": [null, "4.2.0"]}
        # @option {"label": "Swift keystone client version"}
        version: ~
    scw:
        # @schema {"enum": [null, "2.3.1"]}
        # @option {"label": "Scaleway cli version"}
      version: ~
