manala:
    description: Kubernetes cluster administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/make
      - .manala/templates
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: ""
    # @schema {"items": {"type": "string"}}
    mount: []
    kubectl:
        # @schema {"enum": ["1.24.1", "1.23.7", "1.22.10", "1.21.13", "1.20.15", "1.19.16", "1.18.20"]}
        # @option {"label": "Kubectl version"}
        version: ~
    helm:
        # @schema {"enum": [null, "3.9.0", "3.8.2", "3.7.2"]}
        # @option {"label": "Helm version"}
        version: ~
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "url": {"type": "string"},
        #             "path": {"type": "string"},
        #             "version": {"type": "string"}
        #         },
        #         "oneOf": [
        #             {"required": ["url"]},
        #             {"required": ["path"]}
        #         ]
        #     }
        # }
        plugins: []
    helmfile:
        # @schema {"enum": [null, "0.144.0"]}
        # @option {"label": "Helmfile version"}
        version: ~
    k9s:
        # @schema {"enum": [null, "0.25.18"]}
        # @option {"label": "K9s version"}
        version: ~
    stern:
        # @schema {"enum": [null, "1.21.0"]}
        # @option {"label": "Stern version"}
        version: ~
    kube_prompt:
        # @schema {"enum": [null, "1.0.11"]}
        # @option {"label": "Kube Prompt version"}
        version: ~
    popeye:
        # @schema {"enum": [null, "0.10.0"]}
        # @option {"label": "Popeye version"}
        version: ~
    knsk:
        # @schema {"enum": [null, "1.0"]}
        # @option {"label": "Kubernetes namespace killer version"}
        version: ~
    vault:
        # @schema {"enum": [null, "1.10.4", "1.9.7", "1.8.12"]}
        # @option {"label": "Vault version"}
        version: ~
    rclone:
        # @schema {"enum": [null, "1.58.1"]}
        # @option {"label": "Rclone version"}
      version: ~
    openstack:
        # @schema {"enum": [null, "5.8.0"]}
        # @option {"label": "Openstack client version"}
      version: ~
    swift:
        # @schema {"enum": [null, "4.0.0"]}
        # @option {"label": "Swift client version"}
      version: ~
      keystone:
        # @schema {"enum": [null, "4.5.0"]}
        # @option {"label": "Swift keystone client version"}
        version: ~
    scw:
        # @schema {"enum": [null, "2.5.2"]}
        # @option {"label": "Scaleway cli version"}
      version: ~
