manala:
    description: Kubernetes environment, opiniated, docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/make
      - .manala/shell
      - .manala/.gitignore
      - .manala/docker-compose.yaml.tmpl
      - .manala/Dockerfile.tmpl
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    # @schema {"items": {"type": "string"}}
    mount: []
    kubectl:
        # @schema {"enum": ["1.20.5"]}
        # @option {"label": "Kubectl version"}
        version: ~
    helm:
        # @schema {"enum": [null, "3.5.3"]}
        # @option {"label": "Helm version"}
        version: ~
