manala:
    description: Kubernetes cluster administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/etc
      - .manala/github
      - .manala/gitlab
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1, "pattern": "^[a-z0-9][a-z0-9_-]*$"}
    # @option {"label": "Project name"}
    name: ~
    # @schema {"type": ["null", "string"]}
    help: ~

##########
# System #
##########

system:
    dir: ~
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: []
    # @schema {"items": {"type": "string"}}
    mount: []
    docker: false
    goss:
        # @schema {"enum": [null, "0.4.2", "0.3.23"]}
        version: ~
    apt:
        # @schema {"items": {"type": "string"}}
        packages: []
    git:
        # @schema {"type": ["null", "string"]}
        config: ~
    kubectl:
        # @schema {"enum": ["1.28.3", "1.27.7", "1.26.10", "1.25.15", "1.24.17", "1.23.17", "1.22.17", "1.21.14", "1.20.15"]}
        # @option {"label": "Kubectl version"}
        version: ~
    helm:
        # @schema {"enum": [null, "3.13.1", "3.12.3", "3.11.3", "3.10.3"]}
        # @option {"label": "Helm version"}
        version: ~
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "url": {"type": "string"},
        #             "path": {"type": "string"},
        #             "version": {"type": "string"}
        #         },
        #         "oneOf": [
        #             {"required": ["url"]},
        #             {"required": ["path"]}
        #         ]
        #     }
        # }
        plugins: []
    helmfile:
        # @schema {"enum": [null, "0.157.0", "0.156.0"]}
        # @option {"label": "Helmfile version"}
        version: ~
    k9s:
        # @schema {"enum": [null, "0.27.4"]}
        # @option {"label": "K9s version"}
        version: ~
    stern:
        # @schema {"enum": [null, "1.26.0"]}
        # @option {"label": "Stern version"}
        version: ~
    kube-prompt:
        # @schema {"enum": [null, "1.0.11"]}
        # @option {"label": "Kube-prompt version"}
        version: ~
    popeye:
        # @schema {"enum": [null, "0.11.1"]}
        # @option {"label": "Popeye version"}
        version: ~
    knsk:
        # @schema {"enum": [null, "1.0"]}
        # @option {"label": "Kubernetes namespace killer version"}
        version: ~
    vault:
        # @schema {"enum": [null, "1.15.0", "1.14.4", "1.13.8", "1.12.11"]}
        # @option {"label": "Vault version"}
        version: ~
    rclone:
        # @schema {"enum": [null, "1.64.1"]}
        # @option {"label": "Rclone version"}
        version: ~
    openstack:
        # @schema {"enum": [null, "6.3.0"]}
        # @option {"label": "Openstack client version"}
        version: ~
    swift:
        # @schema {"enum": [null, "4.4.0"]}
        # @option {"label": "Swift client version"}
        version: ~
        keystone:
            # @schema {"enum": [null, "5.2.0"]}
            # @option {"label": "Swift keystone client version"}
            version: ~
    scw:
        # @schema {"enum": [null, "2.23.0"]}
        # @option {"label": "Scaleway cli version"}
        version: ~
    sops:
        # @schema {"enum": [null, "3.8.1"]}
        # @option {"label": "Sops version"}
        version: ~
    aws:
        # @schema {"enum": [null, "2.13.27"]}
        # @option {"label": "AWS cli version"}
        version: ~
    gcloud:
        # @schema {"enum": [null, "454.0.0"]}
        # @option {"label": "Google Cloud cli version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        components: []
