manala:
    description: Kubernetes cluster administration environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/etc
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~
    # @schema {"type": ["null", "string"]}
    help: ~

##########
# System #
##########

system:
    dir: ~
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {"type": ["string", "array"]}
    env_file: []
    # @schema {"items": {"type": "string"}}
    mount: []
    docker: false
    kubectl:
        # @schema {"enum": ["1.26.1", "1.25.6", "1.24.10", "1.23.16", "1.22.17", "1.21.14", "1.20.15", "1.19.16", "1.18.20"]}
        # @option {"label": "Kubectl version"}
        version: ~
    helm:
        # @schema {"enum": [null, "3.11.0", "3.10.3", "3.9.4", "3.8.2"]}
        # @option {"label": "Helm version"}
        version: ~
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "url": {"type": "string"},
        #             "path": {"type": "string"},
        #             "version": {"type": "string"}
        #         },
        #         "oneOf": [
        #             {"required": ["url"]},
        #             {"required": ["path"]}
        #         ]
        #     }
        # }
        plugins: []
    helmfile:
        # @schema {"enum": [null, "0.150.0"]}
        # @option {"label": "Helmfile version"}
        version: ~
    k9s:
        # @schema {"enum": [null, "0.26.7"]}
        # @option {"label": "K9s version"}
        version: ~
    stern:
        # @schema {"enum": [null, "1.22.0"]}
        # @option {"label": "Stern version"}
        version: ~
    kube-prompt:
        # @schema {"enum": [null, "1.0.11"]}
        # @option {"label": "Kube-prompt version"}
        version: ~
    popeye:
        # @schema {"enum": [null, "0.10.1"]}
        # @option {"label": "Popeye version"}
        version: ~
    knsk:
        # @schema {"enum": [null, "1.0"]}
        # @option {"label": "Kubernetes namespace killer version"}
        version: ~
    vault:
        # @schema {"enum": [null, "1.12.2", "1.11.6", "1.10.9", "1.9.10"]}
        # @option {"label": "Vault version"}
        version: ~
    rclone:
        # @schema {"enum": [null, "1.61.1"]}
        # @option {"label": "Rclone version"}
      version: ~
    openstack:
        # @schema {"enum": [null, "6.0.0"]}
        # @option {"label": "Openstack client version"}
      version: ~
    swift:
        # @schema {"enum": [null, "4.1.0"]}
        # @option {"label": "Swift client version"}
      version: ~
      keystone:
        # @schema {"enum": [null, "5.0.1"]}
        # @option {"label": "Swift keystone client version"}
        version: ~
    scw:
        # @schema {"enum": [null, "2.8.0"]}
        # @option {"label": "Scaleway cli version"}
      version: ~
    sops:
        # @schema {"enum": [null, "3.7.3"]}
        # @option {"label": "Sops version"}
      version: ~
    aws:
        # @schema {"enum": [null, "2.9.17"]}
        # @option {"label": "AWS cli version"}
      version: ~
