manala:
    description: Kubernetes environment, opiniated, docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/make
      - .manala/shell
      - .manala/docker-compose.yaml.tmpl
      - .manala/Dockerfile.tmpl
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

##########
# System #
##########

system:
    kubectl:
        # @option {"label": "Kubectl version"}
        # @schema {"enum": ["1.20.5"]}
        version: ~
