---

- name: release > Create directory "{{ release_dir }}"
  shell: >
    rm --recursive --force {{ release_dir }}
    && mkdir -p {{ release_dir }}
  args:
    warn: false
  tags: log_failed

################
# Source - Git #
################

- name: git > Get "{{ release_source_repo }}" source repo url
  shell: >
    git config --get remote.origin.url
  args:
    chdir: "{{ release_source_repo }}"
  tags: log_failed
  register: __release_source_repo_url

- name: git > Get "{{ release_source_repo }}" source repo info
  git:
    repo: "{{ __release_source_repo_url.stdout }}"
    dest: "{{ release_source_repo }}"
    clone: false
    update: false
  register: __release_source_repo_info

- name: git > Export "{{ release_source_repo }}" source repo on version "{{ release_source_version }}"
  shell: >
    git archive {{ release_source_version }}{{
      ' ' ~ release_working_dir if (release_working_dir) else ''
    }}
    | tar -x -C {{ release_dir }}{{
        ' ' ~ release_working_dir
        ~ ' --strip-components=' ~ release_working_dir.split('/')|length
          if (release_working_dir) else
        ''
    }}
  args:
    chdir: "{{ release_source_repo }}"
  tags: log_failed

- name: git > Set release message
  set_fact:
     __release_message: |
       {{
         ansible_date_time.year
         ~ ansible_date_time.month
         ~ ansible_date_time.day
         ~ ansible_date_time.hour
         ~ ansible_date_time.minute
         ~ ansible_date_time.second
       }}
       Original commit: https://{{
         __release_source_repo_url.stdout|regex_replace(release_git_url_regex, '\g<host>/\g<user>/\g<repository>')
       }}/commit/{{ __release_source_repo_info.after }}

#########
# Tasks #
#########

- name: release > Execute tasks
  include_tasks: task/{{ item.task }}.yml
  loop: "{{ query('release_tasks', release_tasks) }}"
  when: item.when

##########
# Remove #
##########

- name: release > Remove content
  shell: >
    rm --recursive --force {{ [release_dir, item]|join('/') }}
  args:
    warn: false
  tags: log_failed
  loop: "{{ release_removed }}"

#####################
# Destination - Git #
#####################

- name: git > Init "{{ release_repo }}" destination repo on version "{{ release_version }}"
  shell: >
    git init
    && git checkout -b {{ release_version }}
    && git remote add origin {{ release_repo }}
    && git fetch
    && (
      git show-ref -q origin/{{ release_version }} ; rc=$? ;
      if [ $rc -eq 0 -o $rc -eq 1 ] ; then
        if [ $rc -eq 0 ] ; then
          git update-ref HEAD origin/{{ release_version }} ;
        fi ;
      else
        return $rc ;
      fi
    )
  args:
    chdir: "{{ release_dir }}"
  tags: log_failed

- name: git > Add all content
  shell: >
    git add --force --all
  args:
    chdir: "{{ release_dir }}"
  when: release_add|length == 0
  tags: log_failed

- name: git > Add content
  shell: >
    git add --force {{ item }}
  args:
    chdir: "{{ release_dir }}"
  loop: "{{ release_add }}"
  tags: log_failed

- name: git > Commit release
  shell: >
    git commit -m "{{ __release_message }}" --allow-empty
  args:
    chdir: "{{ release_dir }}"
  tags: log_failed

- name: git > Push "{{ release_version }}" release
  shell: >
    git push --set-upstream origin {{ release_version }}
    && git push origin HEAD
  args:
    chdir: "{{ release_dir }}"
  tags: log_failed
