manala:
    description: Ops environment, opiniated and docker based, for lazy people
    template: .manala.yaml.tmpl
    sync:
      - .manala/docker
      - .manala/etc
      - .manala/github
      - .manala/gitlab
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1, "pattern": "^[a-z0-9][a-z0-9_-]*$"}
    # @option {"label": "Project name"}
    name: ~
    # @schema {"type": ["null", "string"]}
    help: ~

##########
# System #
##########

system:
    dir: ~
    locale: C.UTF-8
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    # @schema {
    #     "type": ["string", "array"],
    #     "items": {"oneOf": [
    #         {"type": "string"},
    #         {
    #             "type": "object",
    #             "properties": {
    #                  "path": {"type": "string"},
    #                  "required": {"type": "boolean"}
    #             },
    #             "required": ["path"],
    #             "additionalProperties": false
    #         }
    #     ]}
    # }
    env_file: []
    # @schema {"items": {"type": "string"}}
    mount: []
    # @schema {"items": {"type": "string"}}
    tmpfs: []
    starship:
        # @schema {"type": ["null", "string"]}
        config: ~
    docker: false
    apt:
        # @schema {"items": {"type": "string"}}
        packages: []
    git:
        # @schema {"type": ["null", "string"]}
        config: ~
    ssh:
        # @schema {"type": ["null", "string"]}
        config: ~
    ansible:
        # @schema {"enum": [null, "2.19.2", "2.18.9", "2.17.14", "2.16.14"]}
        # @option {"label": "Ansible version"}
        version: ~
        # @schema {"type": ["null", "string"]}
        config: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    ansible-lint:
        # @schema {"enum": [null, "25.9.1", "25.7.0", "24.9.2", "24.7.0", "24.6.1", "24.5.0"]}
        # @option {"label": "Ansible-lint version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    ansible-creator:
        # @schema {"enum": [null, "25.9.0"]}
        # @option {"label": "Ansible-creator version"}
        version: ~
    molecule:
        # @schema {"enum": [null, "25.9.0", "25.7.0", "24.9.0", "24.8.0", "24.7.0", "24.6.1"]}
        # @option {"label": "Molecule version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        dependencies: []
    terraform:
        # @schema {"enum": [null, "1.13.3", "1.12.2", "1.11.4", "1.10.5", "1.9.8"]}
        # @option {"label": "Terraform version"}
        version: ~
    kubectl:
        # @schema {"enum": [null, "1.35.0", "1.34.3", "1.33.7", "1.32.11"]}
        # @option {"label": "Kubectl version"}
        version: ~
    kustomize:
        # @schema {"enum": [null, "5.8.0"]}
        # @option {"label": "Kustomize version"}
        version: ~
    krew:
        # @schema {"enum": [null, "0.4.5"]}
        # @option {"label": "Krew version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        plugins: []
    helm:
        # @schema {"enum": [null, "4.1.0", "4.0.5", "3.20.0", "3.19.5", "3.18.6"]}
        # @option {"label": "Helm version"}
        version: ~
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "url": {"type": "string"},
        #             "path": {"type": "string"},
        #             "version": {"type": "string"},
        #             "verify": {"type": "boolean"}
        #         },
        #         "oneOf": [
        #             {"required": ["url"]},
        #             {"required": ["path"]}
        #         ]
        #     }
        # }
        plugins: []
    helmfile:
        # @schema {"enum": [null, "1.2.3", "1.1.9", "0.171.0"]}
        # @option {"label": "Helmfile version"}
        version: ~
    k9s:
        # @schema {"enum": [null, "0.50.18"]}
        # @option {"label": "K9s version"}
        version: ~
    stern:
        # @schema {"enum": [null, "1.33.1"]}
        # @option {"label": "Stern version"}
        version: ~
    popeye:
        # @schema {"enum": [null, "0.22.1"]}
        # @option {"label": "Popeye version"}
        version: ~
    vault:
        # @schema {"enum": [null, "1.21.2", "1.20.4", "1.19.5", "1.18.5"]}
        # @option {"label": "Vault version"}
        version: ~
    rclone:
        # @schema {"enum": [null, "1.72.1"]}
        # @option {"label": "Rclone version"}
        version: ~
    openstack:
        # @schema {"enum": [null, "8.3.0", "7.5.0", "6.6.1"]}
        # @option {"label": "Openstack client version"}
        version: ~
    swift:
        # @schema {"enum": [null, "4.9.0"]}
        # @option {"label": "Swift client version"}
        version: ~
        keystone:
            # @schema {"enum": [null, "5.7.0"]}
            # @option {"label": "Swift keystone client version"}
            version: ~
    scw:
        # @schema {"enum": [null, "2.50.0"]}
        # @option {"label": "Scaleway cli version"}
        version: ~
    sops:
        # @schema {"enum": [null, "3.11.0"]}
        # @option {"label": "Sops version"}
        version: ~
    aws:
        # @schema {"enum": [null, "2.33.4"]}
        # @option {"label": "AWS cli version"}
        version: ~
        # @schema {"type": ["null", "string"]}
        config: ~
    gcloud:
        # @schema {"enum": [null, "553.0.0"]}
        # @option {"label": "Google Cloud cli version"}
        version: ~
        # @schema {"items": {"type": "string"}}
        components: []
    age:
        # @schema {"enum": [null, "1.3.1"]}
        # @option {"label": "Age version"}
        version: ~
    argocd:
        # @schema {"enum": [null, "3.2.5", "3.1.11", "2.14.21"]}
        # @option {"label": "ArgoCD version"}
        version: ~
