printf "          |\n"
printf "        \ _ /     Lazy - Ansible\n"
printf "      -= (_) =-\n"
printf "        /   \         _\/_\n"
printf "          |           //o\  _\/_\n"
printf "   _____ _ __ __ ____ _ | __/o\\ _\n"
printf " =-=-_-__=_-= _=_=-=_,-'|\"'\"\"-|-,_\n"
printf "  =- _=-=- -_=-=_,-\"          |\"\n"
printf "    =- =- -=.--\"\n"
