[hostname]
ssh_only = false
trim_at = ""

[username]
disabled = false
show_always = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true
