manala:
    description: Elao - Generic application with PHP and Node.js support
    sync:
      - .manala/ansible
      - .manala/docker
      - .manala/github
      - .manala/jenkins
      - .manala/make
      - .manala/vagrant
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/Dockerfile.tmpl
      - .manala/Jenkinsfile.tmpl
      - .manala/Makefile.tmpl
      - .manala/Vagrantfile.tmpl
      - .manala.yaml.tmpl.dist
      - Makefile.dist
      - README.md .manala/README.md

##########
# System #
##########

system:
    # @option {"label": "System version"}
    # @schema {"enum": [10, 9, 8]}
    version: ~
    # @option {"label": "Hostname"}
    # @schema {"type": "string", "format": "domain"}
    hostname: ~
    # @schema {"type": ["integer"]}
    memory: 2048
    # @schema {"type": ["integer"]}
    cpus: 1
    motd:
        # @schema {"type": ["string"]}
        template: motd/elao.j2
        # @schema {"type": ["string", "array"]}
        message:
          - A curl vaillant, rien d'impossible !
          - --force et owner !
          - Il n'y pas de question cron, juste des réponses mal timé ! — Cronfucius
    # @schema {"type": ["string"], "pattern": "^[a-zA-Z]+/[a-zA-Z]+$"}
    timezone: Etc/UTC
    locales:
        # @schema {"type": ["string"]}
        default: C.UTF-8
        # @schema {"items": {"type": "string"}}
        codes: []
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    apt:
        # @schema {"items": {"type": "string"}}
        repositories: []
        # @schema {"items": {"type": "string"}}
        preferences: []
        # @schema {"items": {"type": "string"}}
        packages: []
        # @schema {"items": {"type": "string"}}
        holds: []
    # @schema {"items": {"type": "object"}}
    files: []
    nginx:
        # @schema {"items": {"type": "object"}}
        configs: []
    php:
        # @option {"label": "Php version"}
        # @schema {"enum": [null, "8.0", 7.4, 7.3, 7.2, 7.1, "7.0", 5.6]}
        version: ~
        # @schema {"items": {"type": "string"}}
        extensions: []
        # @schema {"items": {"type": "object"}}
        configs: []
        composer:
          # @schema {"enum": [null, 1]}
          version: ~
    cron:
        # @schema {"items": {"type": "object"}}
        files: []
    supervisor:
        # @schema {"items": {"type": "object"}}
        configs: []
    nodejs:
        # @option {"label": "Nodejs version"}
        # @schema {"enum": [null, 14, 12, 10, 8, 6]}
        version: ~
        # @schema {"items": {"type": "object"}}
        packages: []
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.5, 10.4, 10.3, 10.2, 10.1, "10.0"]}
        version: ~
    mysql:
        # @option {"label": "MySQL version"}
        # @schema {"enum": [null, "8.0", 5.7, 5.6]}
        version: ~
    redis:
        # @option {"label": "Redis version"}
        # @schema {"enum": [null, "*"]}
        version: ~
        # @schema {"items": {"type": "object"}}
        config: []
    elasticsearch:
        # @option {"label": "Elasticsearch version"}
        # @schema {"enum": [null, 7, 6, 5, 2, 1.7, 1.6, 1.5]}
        version: ~
        # @schema {"items": {"type": "string"}}
        plugins: []
    influxdb:
        # @option {"label": "InfluxDB version"}
        # @schema {"enum": [null, "*"]}
        version: ~
        # @schema {"items": {"type": "string"}}
        databases: []
        # @schema {"items": {"type": "object"}}
        users: []
        # @schema {"items": {"type": "object"}}
        privileges: []
        # @schema {"items": {"type": "object"}}
        config: []
    ssh:
        client:
            # @schema {"items": {"type": "object"}}
            config: []
    docker:
        # @schema {"items": {"type": "object"}}
        containers: []

###############
# Integration #
###############

# @schema {
#     "definitions": {
#         "integration": {"type": "object", "$id": "#integration",
#             "additionalProperties": false,
#             "properties": {
#                 "label": {"type": "string"},
#                 "parallel": {"type": "boolean"},
#                 "app": {"type": "string", "pattern": "^[a-z]+$"},
#                 "env": {"type": "object",
#                     "additionalProperties": {"type": ["string", "integer"]},
#                     "propertyNames": {"pattern": "^[A-Z_]+$"}
#                 },
#                 "junit": {"type": "string"},
#                 "artifacts": {"type": ["string", "array"]},
#                 "shell": {"type": "string"},
#                 "warn": {"type": "boolean"},
#                 "tasks": {"type": "array", "items": {"$ref": "#integration"}}
#             }
#         }
#     },
#     "$ref": "#integration"
# }
integration: {}

############
# Releases #
############

# @schema {
#     "definitions": {
#         "release": {"type": "object", "$id": "#release",
#             "additionalProperties": false,
#             "properties": {
#                 "app": {"type": "string", "pattern": "^[a-z]+$"},
#                 "mode": {"type": "string", "pattern": "^[\\w-/]+$"},
#                 "repo": {"type": "string", "format": "git-repo"},
#                 "ref": {"type": "string", "pattern": "^[\\w-/]+$"},
#                 "release_tasks": {"type": "array", "items": {"$ref": "#release_task"}},
#                 "release_add": {"type": "array", "items": {"type": "string"}},
#                 "release_removed": {"type": "array", "items": {"type": "string"}},
#                 "deploy_hosts": {"oneOf": [
#                     {"type": "array", "items": {"$ref": "#release_host"}},
#                     {"type": "object", "additionalProperties": {"type": "array", "items": {"$ref": "#release_host"}}}
#                 ]},
#                 "deploy_dir": {"type": "string", "format": "file-path"},
#                 "deploy_releases": {"type": "integer"},
#                 "deploy_tasks": {"type": "array", "items": {"$ref": "#release_task"}},
#                 "deploy_post_tasks": {"type": "array", "items": {"$ref": "#release_task"}},
#                 "deploy_shared_files": {"type": "array", "items": {"type": "string"}},
#                 "deploy_shared_dirs": {"type": "array", "items": {"type": "string"}},
#                 "deploy_writable_dirs": {"type": "array", "items": {"type": "string"}},
#                 "deploy_removed": {"type": "array", "items": {"type": "string"}}
#             },
#             "dependencies": {
#                 "deploy_hosts": ["deploy_dir"]
#             },
#             "required": ["mode", "repo"]
#         },
#         "release_task": {"type": "object", "$id": "#release_task",
#             "additionalProperties": false,
#             "properties": {
#                 "shell": {"type": "string"},
#                 "when": {"type": "string"}
#             }
#         },
#         "release_host": {"type": "object", "$id": "#release_host",
#             "additionalProperties": true,
#             "properties": {
#                 "ssh_host": {"type": "string", "format": "hostname"},
#                 "ssh_user": {"type": "string"},
#                 "ssh_args": {"type": "string"}
#             },
#             "required": ["ssh_host"]
#         }
#     },
#     "items": {"$ref": "#release"}
# }
releases: []
