manala:
    description: Elao - Generic application with PHP and Node.js support
    template: .manala.yaml.tmpl
    sync:
      - .manala/ansible
      - .manala/make
      - .manala/.dockerignore
      - .manala/.gitignore
      - .manala/docker-compose.mutagen.yaml
      - .manala/docker-compose.yaml.tmpl
      - .manala/Dockerfile.tmpl
      - .manala/Makefile.tmpl
      - Makefile.dist
      - README.md .manala/README.md

###########
# Project #
###########

project:
    # @schema {"type": "string", "minLength": 1}
    # @option {"label": "Project name"}
    name: ~

##########
# System #
##########

system:
    # @option {"label": "System version"}
    # @schema {"enum": [11, 10, 9]}
    version: ~
    # @schema {"type": ["string"], "pattern": "^[a-zA-Z]+/[a-zA-Z]+$"}
    timezone: Etc/UTC
    locales:
        # @schema {"type": ["string"]}
        default: C.UTF-8
        # @schema {"items": {"type": "string"}}
        codes: []
    # @schema {
    #     "additionalProperties": {"type": ["string", "integer"]},
    #     "propertyNames": {"pattern": "^[A-Z_]+$"}
    # }
    env: {}
    apt:
        # @schema {"items": {"type": "string"}}
        repositories: []
        # @schema {"items": {"type": "string"}}
        preferences: []
        # @schema {"items": {"type": "string"}}
        packages: []
        # @schema {"items": {"type": "string"}}
        holds: []
    # @schema {"items": {"type": "object"}}
    files: []
    nginx:
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "template": {"type": "string"},
        #             "file": {"type": "string"},
        #             "config": {"type": "string"}
        #         }
        #     }
        # }
        configs: []
    php:
        # @option {"label": "Php version"}
        # @schema {"enum": [null, "8.0", 7.4, 7.3, 7.2, 7.1, "7.0", 5.6]}
        version: ~
        # @schema {"items": {"type": "string"}}
        extensions: []
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "template": {"type": "string"},
        #             "file": {"type": "string"},
        #             "config": {"type": ["object", "string"]}
        #         }
        #     }
        # }
        configs: []
        composer:
          # @schema {"enum": [null, 1]}
          version: ~
    cron:
        # @schema {"items": {"type": "object"}}
        files: []
    supervisor:
        # @schema {"items": {"type": "object"}}
        configs: []
    nodejs:
        # @option {"label": "Nodejs version"}
        # @schema {"enum": [null, 16, 14, 12, 10, 8, 6]}
        version: ~
        # @schema {"items": {"type": "object"}}
        packages: []
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.5, 10.4, 10.3, 10.2, 10.1, "10.0"]}
        version: ~
    ssh:
        client:
            # @schema {"type": ["null", "string"]}
            config: ~
