services:

    ##########
    # System #
    ##########

    system:
        volumes:
            - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
        environment:
            SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
