name: Build Documentation

on:
  workflow_dispatch: ~
  push:
    branches:
      - master

jobs:

  docs:
    name: 🚧  Build & Deploy  🚀
    runs-on: ubuntu-latest

    env:
      working-directory: ./docs/app
    defaults:
      run:
        # https://github.community/t/use-working-directory-for-entire-job/16747/9
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Setup node
        uses: actions/setup-node@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "json"
          ini-values: "memory_limit=-1"
          php-version: "8.0"

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: composer-${{ hashFiles('docs/app/composer.lock') }}
          restore-keys: composer-

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('docs/app/package-lock.json') }}
          restore-keys: node-

      - name: Install dependencies
        run: |
          echo "::group::composer install"
            composer install --no-progress --no-suggest --ansi
          echo "::endgroup::"

          echo "::group::npm install"
            npm install --color=always --no-progress
          echo "::endgroup::"

      - name: Warmup
        run: |
          echo "::group::warmup production env"
            npx encore production --color=always --no-progress
            bin/console cache:clear --ansi
            bin/console cache:warmup --ansi
          echo "::endgroup::"
        env:
          APP_ENV: prod
          WEBPACK_PUBLIC_PATH: /manala-recipes/build

      - name: Build static site
        run: bin/console stenope:build --no-interaction -vv --ansi
        env:
          APP_ENV: prod
          ROUTER_DEFAULT_URI: https://manala.github.io/manala-recipes

      # https://github.com/marketplace/actions/deploy-to-github-pages
      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          COMMIT_MESSAGE: "[AUTO] Static site update"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/app/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
