name: Lazy - Ansible

on:
  pull_request:
    paths:
      - lazy.ansible/**
  workflow_dispatch:

env:
  directory: lazy.ansible/test

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Manala update
        uses: manala/github-action-manala@v1
        with:
          directory: ${{ env.directory }}

      - name: Lint
        working-directory: ${{ env.directory }}
        run: |
          make lint \
            VERBOSE=1

  test:
    name: Test
    runs-on: ubuntu-22.04
    env:
      MANALA_DOCKER_CACHE_FROM: type=gha,scope=docker.lazy.ansible
      MANALA_DOCKER_CACHE_TO: type=gha,mode=max,scope=docker.lazy.ansible
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Manala update
        uses: manala/github-action-manala@v1
        with:
          directory: ${{ env.directory }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Expose ACTIONS_CACHE_URL & ACTIONS_RUNTIME_TOKEN
      # to be consumed by docker github action cache
      # See: https://docs.docker.com/build/cache/backends/gha/
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      - name: Test
        working-directory: ${{ env.directory }}
        run: |
          make test
